### ISSUE TITLE
2a Task 1 流程執行查驗回報

### ISSUE THREAD

**Issue by mdecourse** [mdecourse/cad2019#15]
Task1 所需完成事項如下:

1. 利用 Solvespace 繪製雙輪車所需的零組件, 將操作過程拍成帶有說明字幕的影片後上傳至 Youtube 後, 嵌入個人網頁 W6 頁面中. (影片標題為: 機械設計工程系-電腦輔助設計實習 W6 任務一參數化零組件繪製).
2. 利用 V-rep 3.6.1 rev4 與隨身程式執行系統, 完成網際 V-rep 模型控制任務後, 將操作過程拍成帶有說明字幕的影片後上傳至 Youtube 後, 嵌入個人網頁 W6 頁面中. (影片標題為: 機械設計工程系-電腦輔助設計實習 W6 任務一網際 V-rep 模型控制).
3. 從 https://github.com/mdecourse/cad2019/issues/14 已知可透過 Python 程式啟動或停止 V-rep 模擬, 請在事項 2 的架構下, 新增兩個按鈕, 可以啟動或停止所連線的 V-rep 模擬. 完成後將操作流程拍成帶字幕的影片後上傳至 Youtube 後, 嵌入個人網頁 W6 頁面中. (影片標題為: 機械設計工程系-電腦輔助設計實習 W6 任務一新增啟動與停止按鈕).

請各組員在完成各分項任務後, 透過下列回報個人網頁中的 W6 頁面連結.

**Comment by s40723145** [comment]
https://s40723145.github.io/cad2019/content/Week6.html
