### ISSUE TITLE
2b Task 1 流程執行查驗回報

### ISSUE THREAD

**Issue by mdecourse** [mdecourse/cad2019#16]
Task1 所需完成事項如下:

1. 利用 Solvespace 繪製雙輪車所需的零組件, 將操作過程拍成帶有說明字幕的影片後上傳至 Youtube 後, 嵌入個人網頁 W6 頁面中. (影片標題為: 機械設計工程系-電腦輔助設計實習 W6 任務一參數化零組件繪製).
2. 利用 V-rep 3.6.1 rev4 與隨身程式執行系統, 完成網際 V-rep 模型控制任務後, 將操作過程拍成帶有說明字幕的影片後上傳至 Youtube 後, 嵌入個人網頁 W6 頁面中. (影片標題為: 機械設計工程系-電腦輔助設計實習 W6 任務一網際 V-rep 模型控制).
3. 從 #14 已知可透過 Python 程式啟動或停止 V-rep 模擬, 請在事項 2 的架構下, 新增兩個按鈕, 可以啟動或停止所連線的 V-rep 模擬. 完成後將操作流程拍成帶字幕的影片後上傳至 Youtube 後, 嵌入個人網頁 W6 頁面中. (影片標題為: 機械設計工程系-電腦輔助設計實習 W6 任務一新增啟動與停止按鈕).

請各組員在完成各分項任務後, 透過下列回報個人網頁中的 W6 頁面連結.

**Comment by s40723210** [comment]
https://s40723210.github.io/cad2019/content/Weekly%20course.html

**Comment by s40723221** [comment]
https://s40723221.github.io/cad2019/content/week2-9.html

**Comment by s40723204** [comment]
https://s40723204.github.io/cad2019/content/WEEK2~9.html

**Comment by s40723201** [comment]
https://s40723244.github.io/cad2019/content/week6.html

**Comment by s40723227** [comment]
https://s40723227.github.io/cad2019/content/Week6~Week7.html

**Comment by s40723242** [comment]
https://s40723242.github.io/cad2019/content/index.html

**Comment by s40723203** [comment]
https://s40723203.github.io/cad2019/content/index.html

**Comment by s40723237** [comment]
https://s40723237.github.io/cad2019/content/index.html

**Comment by s40723240** [comment]
https://s40723240.github.io/cad2019/content/index.html

**Comment by s40723243** [comment]
https://s40723243.github.io/cad2019/content/index.html

**Comment by s40723219** [comment]
https://s40723219.github.io/cad2019/content/index.html

**Comment by s40723206** [comment]
https://s40723206.github.io/cad2019/content/index.html

**Comment by s40723212** [comment]
[https://s40723212.github.io/cad2019/content/week6-9.html](url)

**Comment by s40723209** [comment]
https://s40723209.github.io/cad2019/content/week6~9.html

**Comment by s40723213** [comment]
https://s40723213.github.io/cad2019/content/Week6-9.html

**Comment by s40723201** [comment]
https://s40723201.github.io/cad2019/content/Week%206-9.html
