### ISSUE TITLE
2a W7 Solvespace 編譯與參數繪圖驗證回報

### ISSUE THREAD

**Issue by mdecourse** [mdecourse/cad2019#17]
請分別完成 W7 週所指定的驗證項目後, 在下列回應中填入所完成的內容連結.

回應內容範例:

1. 回報所完成的網頁連結, 例如: http://mde.tw/cad2019/content/Solvespace%20%E7%B7%A8%E8%AD%AF.html

2. 將已經上傳 Youtube 的影片連結納入 issues 回應中, 例如:

    [![Solvespace 編譯說明](http://img.youtube.com/vi/MChuv_rFSXY/0.jpg)](https://www.youtube.com/watch?v=MChuv_rFSXY)

    上述影片連結所使用的語法:

    `[![Solvespace 編譯說明](http://img.youtube.com/vi/MChuv_rFSXY/0.jpg)](https://www.youtube.com/watch?v=MChuv_rFSXY)`

    其中的 "MChuv_rFSXY" 為 Youtube 影片編號.

**Comment by s40723145** [comment]
https://s40723145.github.io/cad2019/content/Week7.html
[![Solvespace 編譯說明](http://img.youtube.com/vi/EyeHK5kWwlo/0.jpg)](https://www.youtube.com/watch?v=EyeHK5kWwlo)
[![Solvespace 編譯說明](http://img.youtube.com/vi/yzimdl6ouTQ/0.jpg)](https://www.youtube.com/watch?v=yzimdl6ouTQ)

**Comment by s40723150** [comment]
網頁連結：
solvespace 編譯https://s40723150.github.io/cad2019/content/Solvespace%20%E7%B7%A8%E8%AD%AF.html
繪圖驗證
https://s40723150.github.io/cad2019/content/Solvespace%20%E6%93%8D%E4%BD%9C.html
繪圖驗證 7
[![Solvespace 編譯說明](http://img.youtube.com/vi/KbynRpoET_4/0.jpg)](https://www.youtube.com/watch?v=KbynRpoET_4)
繪圖驗證 10
[![Solvespace 編譯說明](http://img.youtube.com/vi/U6cAGaNZaQ0/0.jpg)](https://www.youtube.com/watch?v=U6cAGaNZaQ0)

**Comment by s40723123** [comment]
繪圖驗證 8
[![Solvespace 編譯說明](http://img.youtube.com/vi/2OGZmDBsTm0/0.jpg)](https://www.youtube.com/watch?v=2OGZmDBsTm0)

**Comment by s40723147** [comment]
網頁連結: https://s40723147.github.io/cad2019/content/%E7%B9%AA%E5%9C%96%E8%AA%8D%E8%AD%89%E7%AF%84%E4%BE%8B.html

Solvespace 繪圖驗證(範例1)
[![Solvespace 編譯說明](http://img.youtube.com/vi/cRKKRkRkNlI/0.jpg)](https://www.youtube.com/watch?v=cRKKRkRkNlI)

Solvespace 繪圖驗證(範例2)
[![Solvespace 編譯說明](http://img.youtube.com/vi/8Hdx4pcZ5Ac/0.jpg)](https://www.youtube.com/watch?v=8Hdx4pcZ5Ac)

Solvespace 繪圖驗證(範例3)
[![Solvespace 編譯說明](http://img.youtube.com/vi/eIcolUgQc4Q/0.jpg)](https://www.youtube.com/watch?v=eIcolUgQc4Q)

**Comment by s40723112** [comment]
編譯連結:https://s40723112.github.io/cad2019/content/%E7%B7%A8%E8%AD%AF.html

Solvespace 繪圖驗證 18
[![Solvespace 編譯說明](http://img.youtube.com/vi/y5uVrumE9ug/0.jpg)](https://www.youtube.com/watch?v=y5uVrumE9ug)

**Comment by s40723114** [comment]
編譯連結:
https://s40723114.github.io/cad2019/content/week3.html
繪圖驗證:
https://s40723114.github.io/cad2019/content/week7.html

Solvespace 繪圖驗證 8
https://www.youtube.com/watch?v=LegEE9iwB20&t=110sv%3DMChuv_rFSXY

Solvespace 繪圖驗證 11
https://www.youtube.com/watch?v=gQvkqP0U2bs&t=324sv%3DMChuv_rFSXY
