### ISSUE TITLE
2b W7 Solvespace 編譯與參數繪圖驗證回報

### ISSUE THREAD

**Issue by mdecourse** [mdecourse/cad2019#18]
請分別完成 W7 週所指定的驗證項目後, 在下列回應中填入所完成的內容連結.

回應內容範例:

1. 回報所完成的網頁連結, 例如: http://mde.tw/cad2019/content/Solvespace%20%E7%B7%A8%E8%AD%AF.html

2. 將已經上傳 Youtube 的影片連結納入 issues 回應中, 例如:

    [![V-rep 模擬範例](http://img.youtube.com/vi/TTHOKMq74RE/0.jpg)](https://www.youtube.com/watch?v=TTHOKMq74RE)

    上述影片連結所使用的語法:

    `[![V-rep 模擬範例](http://img.youtube.com/vi/TTHOKMq74RE/0.jpg)](https://www.youtube.com/watch?v=TTHOKMq74RE)`

    其中的 "TTHOKMq74RE" 為 Youtube 影片編號.

**Comment by s40723210** [comment]
網頁連結:https://s40723210.github.io/cad2019/content/Week6-9.html

Solvespace 繪圖驗證:
[![Solvespace 繪圖驗證](http://img.youtube.com/vi/AKpY8QwDO6s/0.jpg)](https://www.youtube.com/watch?v=AKpY8QwDO6s)

**Comment by s40723221** [comment]
網頁連結:https://s40723221.github.io/cad2019/content/week6-9.html
Solvespace 繪圖驗證:
[![week7](http://img.youtube.com/vi/FdNvkbKEUZ4/0.jpg)](https://www.youtube.com/watch?v=FdNvkbKEUZ4)

**Comment by s40723207** [comment]
網頁連結:https://s40723207.github.io/cad2019/content/Week6~Week9.html
[![solvespace繪圖](http://img.youtube.com/vi/AAwnnB84t7g/0.jpg)]

**Comment by s40723227** [comment]
網頁連結:https://s40723227.github.io/cad2019/content/Week6~Week9.html
Solvespace 繪圖驗證:
[![V-rep 模擬範例](http://img.youtube.com/vi/1NI-odKzHzY0.jpg)]
(https://youtu.be/1NI-odKzHzY)

**Comment by s40723242** [comment]
網頁連結:https://s40723242.github.io/cad2019/content/week6-9.html
Solvespace 繪圖驗證:
1.
[![V-rep 模擬範例](http://img.youtube.com/vi/tZ0Am3FjN1I/0.jpg)]
3.
4.
5.
6.
7.
8.
9.
10.
11.
12.
13.
14.
15.
16.
17.
18.

**Comment by s40723242** [comment]
網頁連結:https://s40723242.github.io/cad2019/content/week6-9.html
 Solvespace 繪圖驗證:
1.
![V-rep 模擬範例](http://img.youtube.com/vi/tZ0Am3FjN1I/0.jpg)
3.
![V-rep 模擬範例](http://img.youtube.com/vi/GW9mh6UYG5A/0.jpg)
4.
![V-rep 模擬範例](http://img.youtube.com/vi/uor74DHERw0/0.jpg)
5.
![V-rep 模擬範例](http://img.youtube.com/vi/42m0184pCTY/0.jpg)
6.
![V-rep 模擬範例](http://img.youtube.com/vi/BYa48yTQnM0/0.jpg)
7.
![V-rep 模擬範例](http://img.youtube.com/vi/NjjxOqJZJvA/0.jpg)
8.
![V-rep 模擬範例](http://img.youtube.com/vi/QSvJ23dUi0s/0.jpg)
9.
![V-rep 模擬範例](http://img.youtube.com/vi/kP4T6Gunj8U/0.jpg)
10.
![V-rep 模擬範例](http://img.youtube.com/vi/QYxpaoiKn9E/0.jpg)
11.
![V-rep 模擬範例](http://img.youtube.com/vi/BW83OKLwIBY/0.jpg)
12.
![V-rep 模擬範例](http://img.youtube.com/vi/3l4LUOuc6sY/0.jpg)
13.
![V-rep 模擬範例](http://img.youtube.com/vi/7SoZKtsOEwA/0.jpg)
14.
![V-rep 模擬範例](http://img.youtube.com/vi/OcGAmy0dP24/0.jpg)
15.
![V-rep 模擬範例](http://img.youtube.com/vi/78D6VarVy1U/0.jpg)
16.
![V-rep 模擬範例](http://img.youtube.com/vi/yEE_vYdB7Nw/0.jpg)
17.
![V-rep 模擬範例](http://img.youtube.com/vi/VhXcl4dFByo/0.jpg)
18.
![V-rep 模擬範例](http://img.youtube.com/vi/vQYwmVp5oEQ/0.jpg)

**Comment by s40723204** [comment]
https://s40723204.github.io/cad2019/content/week6-9.html
http://img.youtube.com/vi/wy8zfTwbQhY/0.jpg

**Comment by s40723201** [comment]
網頁連結:https://s40723244.github.io/cad2019/content/week7.html
Solvespace 繪圖驗證:
1.
[![1](http://img.youtube.com/vi/pwSkOWmmpHY/0.jpg)](https://www.youtube.com/watch?v=pwSkOWmmpHY)

**Comment by s40723203** [comment]
網頁連結:https://s40723203.github.io/cad2019/content/week6-9.html
[[![V-rep 模擬範例](http://img.youtube.com/vi/JJyDbIbfgv8/0.jpg)]](https://youtu.be/JJyDbIbfgv8)

**Comment by s40723240** [comment]
網頁連結:https://s40723240.github.io/cad2019/content/Week6-9.html
solvespace繪圖驗證:
1.
[![繪圖驗證1](http://img.youtube.com/vi/bTkosqc0zJw/0.jpg)](https://www.youtube.com/watch?v=bTkosqc0zJw)
3.
[![繪圖驗證3](http://img.youtube.com/vi/fRBtJKjSkO8/0.jpg)](https://www.youtube.com/watch?v=fRBtJKjSkO8)

**Comment by s40723243** [comment]
網站連結:https://s40723243.github.io/cad2019/content/week6-9.html
[[![V-rep 模擬範例](http://img.youtube.com/vi/2GCNcJ7J2ko/0.jpg)]](:https://www.youtube.com/watch?v=2GCNcJ7J2ko)

**Comment by s40723219** [comment]
https://s40723219.github.io/cad2019/content/week7.html 
[[![V-rep 模擬範例](http://img.youtube.com/vi/tGt6INP81TU&feature/0.jpg)]](https://www.youtube.com/watch?v=tGt6INP81TU&feature=youtu.be)

**Comment by s40723219** [comment]
https://s40723219.github.io/cad2019/content/week7.html
[![V-rep 模擬範例](http://img.youtube.com/vi/tGt6INP81TU&feature=youtu.be/0.jpg)]
(https://www.youtube.com/watch?v=tGt6INP81TU&feature=youtu.be)

**Comment by s40723219** [comment]
https://s40723219.github.io/cad2019/content/week7.html
[![V-rep 模擬範例](http://img.youtube.com/vi/tGt6INP81TU&feature=youtu.be/0.jpg)](https://www.youtube.com/watch?v=tGt6INP81TU&feature=youtu.be)

**Comment by s40723219** [comment]
https://s40723219.github.io/cad2019/content/week7.html
[![V-rep 模擬範例](https://img.youtube.com/vi/tGt6INP81TU/0.jpg)](https://www.youtube.com/watch?v=tGt6INP81TU&feature=youtu.be)

**Comment by s40723246** [comment]
[[![V-rep 模擬範例](http://img.youtube.com/vi/1K6_9GAaF_Q/0.jpg)]](https://www.youtube.com/watch?v=1K6_9GAaF_Q)
網站網址:https://s40723246.github.io/cad2019/content/index.html

**Comment by s40723246** [comment]
> 個人網站https://s40723219.github.io/cad2019/content/week7.html
> [![V-rep 模擬範例](https://camo.githubusercontent.com/c3092a1257272fd09ba479733ec19f4ebe6fd46f/68747470733a2f2f696d672e796f75747562652e636f6d2f76692f74477436494e50383154552f302e6a7067)](https://www.youtube.com/watch?v=tGt6INP81TU&feature=youtu.be)

**Comment by s40723247** [comment]
[[![V-rep 模擬範例](http://img.youtube.com/vi/5nOXEHBlboU/0.jpg)]](https://www.youtube.com/watch?v=5nOXEHBlboU)

**Comment by s40739214** [comment]
網頁連結：https://s40739214.github.io/cad2019/content/week6-9.html
Solvespace繪圖驗證:
1.
[![1](http://img.youtube.com/vi/QiGQXbg5Xf4/0.jpg)](https://www.youtube.com/watch?v=QiGQXbg5Xf4)
