### ISSUE TITLE
W9 期中考週任務規劃

### ISSUE THREAD

**Issue by mdecourse** [mdecourse/cad2019#22]
# 各學員製作帶字幕期中報告影片
影片必須加上期中考時段所宣布的內容浮水印後, 上傳至 Youtube 嵌入個人網誌後回報至特定位置
# 利用 Ethercalc 取各學員自評成績

https://ethercalc.net/
# 執行  Webots Tutorial
https://cyberbotics.com/doc/guide/tutorials

各 Tutorial 執行完成後, 必須將心得放入個人 Pelican 網誌中.

**Comment by s40723112** [comment]
s40723112 在blog新增期中報告影片
https://s40723112.github.io/cad2019/blog/pages/about/index.html

**Comment by s40723114** [comment]
s40723114在blog新增期中報告影片
https://s40723114.github.io/cad2019/blog/pages/about/index.html

**Comment by s40723111** [comment]
s40723111 在blog新增期中報告影片
https://s40723111.github.io/cad2019/blog/pages/about/index.html

**Comment by s40723110** [comment]
s40723110 在blog新增期中報告影片
https://s40723110.github.io/cad2019/blog/pages/about/index.html

**Comment by 40823127** [comment]
s40723123 在blog新增期中報告影片
https://s40723123.github.io/cad2019/blog/pages/about/index.html

**Comment by s40723124** [comment]
s40723124 在blog新增期中報告影片
https://s40723124.github.io/cad2019/blog/pages/about/index.html
