### ISSUE TITLE
cad2019 2a 期中報告任務回報

### ISSUE THREAD

**Issue by mdecourse** [mdecourse/cad2019#23]
# 各學員製作帶字幕期中報告影片
影片必須加上期中考時段所宣布的內容浮水印後, 上傳至 Youtube 嵌入個人網誌後回報至下列回應.

例如:

http://mde.tw/cad2019/blog/2019-Fall-Win10-1903.html

**Comment by s40723111** [comment]
s40723111 在blog新增期中報告影片
https://s40723111.github.io/cad2019/blog/pages/about/index.html

**Comment by s40723110** [comment]
s40723110 在blog新增期中報告影片
https://s40723110.github.io/cad2019/blog/pages/about/index.html

**Comment by s40723125** [comment]
s40723125 在blog新增期中報告影片
https://s40723125.github.io/cad2019/blog/pages/about/index.html

**Comment by s40723108** [comment]
s40723108 在blog新增期中報告影片
https://s40723108.github.io/cad2019/blog/pages/about/index.html

**Comment by 40823246** [comment]
s40723150 在blog新增期中報告影片
https://s40723150.github.io/cad2019/blog/pages/about/index.html

**Comment by s40723119** [comment]
s40723119 在blog新增期中報告影片
https://s40723119.github.io/cad2019/blog/pages/about/index.html

**Comment by s40723124** [comment]
s40723119 在blog新增期中報告影片
https://s40723124.github.io/cad2019/blog/pages/about/index.html

**Comment by s40723124** [comment]
s40723124 在blog新增期中報告影片
https://s40723124.github.io/cad2019/blog/pages/about/index.html

**Comment by s40723150** [comment]
s40723150 在blog新增期中報告影片
https://s40723150.github.io/cad2019/blog/pages/about/index.html

**Comment by s40723112** [comment]
s40723112 在blog新增期中報告影片
https://s40723112.github.io/cad2019/blog/pages/about/index.html

**Comment by s40723107** [comment]
s40723107 在blog新增期中報告影片
https://s40723107.github.io/cad2019/blog/pages/about/index.html

**Comment by 40823238** [comment]
s40723147 在blog新增期中報告影片
https://s40723147.github.io/cad2019/blog/index.html

**Comment by s40723147** [comment]
s40723107 在blog新增期中報告影片
https://s40723147.github.io/cad2019/blog/index.html

**Comment by s40523113** [comment]
https://s40523113.github.io/cad2019/blog/2019cad%20embed%20video.html

**Comment by s40723114** [comment]
s40723114在blog新增期中報告影片
https://s40723114.github.io/cad2019/blog/pages/about/index.html

**Comment by s40723148** [comment]
https://s40723148.github.io/cad2019/blog/pages/about/index.html

**Comment by s40723130** [comment]
https://www.youtube.com/watch?v=gJcVGWe2kkI&feature=youtu.be[](url)

**Comment by s40723145** [comment]
https://s40723145.github.io/cad2019/blog/CAD2019.html

**Comment by s40723102** [comment]
https://s40723102.github.io/cad2019/blog/pages/about/index.html

**Comment by s40723118** [comment]
s40723118 在blog新增期中報告影片
https://s40723118.github.io/cad2019/blog/pages/about/index.html

**Comment by s40723120** [comment]
https://s40723120.github.io/cad2019/blog/pages/about/index.html

**Comment by s40723146** [comment]
s40723146 在blog新增期中報告影片
https://s40723146.github.io/cad2019/blog/pages/about/index.html

**Comment by s40723137** [comment]
s40723137 在blog新增期中報告影片
https://s40723137.github.io/cad2019/blog/pages/about/index.html

**Comment by s40723101** [comment]
s40723101 在blog新增期中報告影片
https://s40723101.github.io/cad2019/blog/pages/about/index.html

**Comment by s40723115** [comment]
https://s40723115.github.io/cad2019/blog/pages/about/index.html

**Comment by s40723152** [comment]
s40723152 在blog新增期中報告影片
https://s40723152.github.io/cad2019/blog/pages/about/index.html
