### ISSUE TITLE
cad2019 2b 期中報告任務回報

### ISSUE THREAD

**Issue by mdecourse** [mdecourse/cad2019#26]
# 各學員製作帶字幕期中報告影片
影片必須加上期中考時段所宣布的內容浮水印後, 上傳至 Youtube 嵌入個人網誌後回報至下列回應.

例如:

http://mde.tw/cad2019/blog/2019-Fall-Win10-1903.html

**Comment by s40723210** [comment]
https://s40723210.github.io/cad2019/blog/2018-Fall-32-bit-Windows-w9.html

**Comment by s40723221** [comment]
https://s40723221.github.io/cad2019/blog/2018-Fall-32-bit-Windows.html

**Comment by s40723244** [comment]
https://s40723244.github.io/cad2019/blog/2019-Fall-win10-40723244-1903.html

**Comment by s40723201** [comment]
https://s40723201.github.io/cad2019/blog/pages/about/index.html

**Comment by s40723240** [comment]
https://s40723240.github.io/cad2019/blog/2018-Fall-32-bit-Windows.html

**Comment by s40723238** [comment]
https://s40723238.github.io/cad2019/blog/index.html

**Comment by s40723247** [comment]
https://s40723247.github.io/cad2019/blog/index.html

**Comment by s40723218** [comment]
https://s40723218.github.io/cad2019/blog/2018-Fall-32-bit-Windows.html

**Comment by s40723207** [comment]
https://s40723207.github.io/cad2019/blog/cad2019-32-bit-Windows.html

**Comment by s40723227** [comment]
https://s40723227.github.io/cad2019/blog/cad2019-Fall-32-bit-Windows.html

**Comment by s40723206** [comment]
https://s40723206.github.io/cad2019/blog/2018-Fall-32-bit-Windows%20w9.html

**Comment by s40723204** [comment]
https://s40723204.github.io/cad2019/blog/2018-Fall-32-bit-Windows%20w9.html

**Comment by s40723203** [comment]
https://s40723203.github.io/cad2019/blog/2018-Fall-32-bit-Windows%20W9.html

**Comment by s40723246** [comment]
https://s40723246.github.io/cad2019/blog/2018-Fall-32-bit-Windows%20w9.html

**Comment by s40723219** [comment]
https://www.youtube.com/watch?v=k2wj2MUVn54&feature=youtu.be

**Comment by s40723249** [comment]
https://s40723249.github.io/cad2019/blog/s40723249-cad2019.html

**Comment by s40523241** [comment]
[https://s40523241.github.io/cad2019/blog/2019-Fall-Win10-1108.html](https://s40523241.github.io/cad2019/blog/2019-Fall-Win10-1108.html)

**Comment by s40723142** [comment]
https://s40723142.github.io/cad2019/blog/pages/about/index.html

**Comment by s40723219** [comment]
https://s40723219.github.io/cad2019/blog/dian-nao-fu-zhu-she-ji-qi-zhong-bao-gao.html

**Comment by s40723242** [comment]
老師非常不好意思，因為敝人的usb放在宿舍忘了拿回來無法做網誌的編輯，但內容還是有做的，希望老師可以斟酌看一下，下週回去一定會補編輯回來的實在是非常抱歉
內容:
期中報告心得:
從第二週我們用到大一所學的github進行網站編譯及維護，第三周開始一直到第九週使用solvespace進行繪製零件模型並使用V-rep進行動態測試，雖然因程式碼不公開不交了但仍然是一個值得學習的程式後續接替的Webots，都是模擬模型的軟體，但看起來非常複雜，未來還需要花很多心思去了解.

期中報告影片:
"https://www.youtube.com/embed/R1yTnufqg08

課程回顧:
W2:建立個人倉儲並編譯網站

W3:透過Solvespace引導式編譯 進行編譯並啟動

W4:自行維護網站 並在影片中放入字幕及浮水印

W5:進行初步練習並繪製Solvespace零件

W6:
Task1:參數化零組件繪製

Task2:網際 V-rep 模型控制

Task3:新增啟動與停止按鈕

W7:
TASK1:Solvespace 編譯:參數化零組件繪製-About中加上學號

TASK2:Solvespace 參數繪圖驗證

W8:
Task1:啟用 CMSiMDE中的網誌系統

Task2:導入 Webots

Task3:以ssh對Github 連線

**Comment by s40723209** [comment]
https://s40723209.github.io/cad2019/blog/cad2019-Fall-32-bit-Windows.html

**Comment by s40723243** [comment]
https://s40723243.github.io/cad2019/blog/2018-Fall-32-bit-Windows%20W9.html

**Comment by s40723232** [comment]
https://s40723232.github.io/cad2019/blog/s40723232qi-zhong-bao-gao.html

**Comment by s40723212** [comment]
https://s40723212.github.io/cad2019/blog/2018-Fall-32-bit-Windows.html

**Comment by s40723219** [comment]
https://s40723219.github.io/cad2019/blog/dian-nao-fu-zhu-she-ji-qi-zhong-bao-gao.html

**Comment by s40723250** [comment]
https://s40723250.github.io/cad2019/blog/cad2019.html

**Comment by s40723234** [comment]
https://s40723234.github.io/cad2019/blog/qi-zhong-bao-gao.html

**Comment by s40723229** [comment]
https://s40723229.github.io/cad2019/blog/2019-Fall%20w1-w9.html

**Comment by s40723241** [comment]
https://s40723241.github.io/cad2019/blog/2018-Fall-32-bit-Windows%20W9.html

**Comment by s40723223** [comment]
https://s40723223.github.io/cad2019/blog/2018-Fall-32-bit-Windows.html

**Comment by s40723115** [comment]
https://s40723115.github.io/cad2019/blog/pages/about/index.html

**Comment by s40723222** [comment]
https://s40723222.github.io/cad2019/blog/Cad2019-Fall-32-bit-Windows.html

**Comment by s40739214** [comment]
https://s40739214.github.io/cad2019/blog/index.html

**Comment by s40723213** [comment]
https://s40723213.github.io/cad2019/blog/index.html

**Comment by s40723237** [comment]
https://s40723237.github.io/cad2019/blog/2018-Fall-32-bit-Windows.html

**Comment by s40723216** [comment]
https://s40723216.github.io/cad2019/blog/index.html
