### ISSUE TITLE
倉儲、網頁、網誌與簡報協同議題

### ISSUE THREAD

**Issue by scrum-1** [mdecourse/cad2019#29]
# 利用 Travis CI/CD 建立網誌頁面

Pelican 網誌系統在 markdown 目錄中放置 .md 檔案, 可以透過 .travis.yml 進行轉檔整合與網誌部署:

    # Travis-CI yaml setting for CMSiMDE site
    language: python
    os: linux
    sudo: required
    python: "3.7"
    dist: xenial
    install:
      - pip install -r requirements.txt -U
    script:
      - pelican markdown -o blog -s publishconf.py
    deploy:
      provider: pages
      skip_cleanup: true
      github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
      keep_history: true
      target_branch: master
      on:
        branch: master

其中的 $GITHUB_TOKEN 為 Travis CI/CD 系統下的環境變數設定, 其內容
取自 Github 對應帳號下的 Settings - Developer settings 下所產生的 Personal access tokens 字串, 主要用於讓 Travis CI/CD 系統可以有權限更改對應帳號下的倉儲內容.

其他有關 CMSiMDE 與 Reveal 內容建立與檔案轉換流程, 也可以設法採用相同方式處理, 讓各使用者可以直接在網際環境中進行協同.

# requirements.txt 內容

     flask
     bs4
     lxml
     markdown
     pelican
     flask_cors

**Comment by mdecourse** [comment]
# Reveal.js Markdown 方案
https://github.com/humrochagf/revelation
https://github.com/KmolYuan/blank-reveal-yml
https://github.com/LKI/md2reveal

# Markdown to html in Javascript
https://github.com/showdownjs/showdown

**Comment by mdecourse** [comment]
# Travis-CI 目前比較適合 release 套件, 而不適合 CMSiMDE 協同
因為目前只有網誌採用 Markdown 格式, 且當 Travis-CI 將 Markdown 目錄下的 md 轉為 blog 中的網誌文章後, 使用者在近端必須要 git pull 下來合併 blog, 並且在下次提交推送時, 仍然必須設法轉出合用的 blog 網誌文章, 感覺在近端使用  Leo Editor 編輯, 並且設法同步至 blogger 的流程更為實用.

https://2019wcm.blogspot.com/2019/03/posted-via-python.html

**Comment by KmolYuan** [comment]
目前 [Reveal.yml](https://github.com/KmolYuan/blank-reveal-yml) 即採用 [JamesIves/github-pages-deploy-action](https://github.com/JamesIves/github-pages-deploy-action) 部署。

可參考 `.github/workflows/deploy.yml` 的內容。
