### ISSUE TITLE
W15 2a 學員個人學習成果回報考試

### ISSUE THREAD

**Issue by mdecourse** [mdecourse/cad2019#31]
# W15 2a  查驗

請 2a 每位學員在 12:00 之前, 錄製一個至多 3 分鐘帶說明字幕的影片, 說明至今與本課程相關, 所完成的重要內容, 完成後將影片上傳至個人 Youtube 帳號下, 嵌入個人 W15 網頁後, 將倉儲提交連結與影片連結放入下列回應區, 並在回應區寫上個人詳細學習心得.

**Comment by s40723134** [comment]
影片:無
心得:目前還沒有任何進度,剩下一個月得努力追了

**Comment by s40723125** [comment]
倉儲網址
https://s40723125.github.io/cad2019/content/week15.html
影片
https://www.youtube.com/watch?v=eLJBAL1s2Wg
心得˙:從第10周開始處理分組網站外加NX12 、webots 、solvespace 、soildworks、v-rep 等程式每個都需要花時間去學習，要瞭解老師所提供的這些工具真的非常的難，像是裝可攜版的NX12就要佔掉20幾GB，加上我的USB才32GB，假如有機會買入隨身硬碟的話一定很方便。說真的老師教的webots導入 模主壤他跑起來真的很厲害。

**Comment by s40723145** [comment]
倉儲提交連結:
https://github.com/s40723145/cad2019/commits/master
影片連結:
https://youtu.be/Yoi-Bgj4TcU
學習心得:
期中過後至week15將主要的學習重點放在Webot和Vrep的模擬練習，在這兩套軟體中主要學到了如何分析模型，並了解要模擬的話需要有很多參數的調整才能夠完整的將模擬執行順暢。在設定模擬參數中也更能知道特定參數如果沒有設定亦或者設定不完全很容易導致模擬出現瑕疵甚至連動都有問題。

**Comment by s40723103** [comment]
倉儲網址:https://s40723103.github.io/cad2019/content/Week15.html
影片連結:https://www.youtube.com/watch?v=MmWoS78phjE
心得:  在這6週裡學到了關於nx、solvespace、webots、solidwork、v-rep相關知識，也了解老師為何都只上一些就跳到下一個步驟，就是為了先讓學生自行產生興趣再去自行學習，儘管如此，龐大的資訊量與軟件相關設定步驟等等諸如此類的東西在整理筆記時也重新審視這一週的收穫，操作影片過程有時也會遇到指令看不懂與操作失誤的部分，同時也累積自身學習體驗的經歷，整體來說，是收穫不少，可能因時間倉促的因素讓進度的步調顯得有些快，不過也讓人印象深刻。

**Comment by s40723121** [comment]
[https://www.youtube.com/watch?v=fZ1AZxOmOQ8&feature=youtu.be](url)
我覺得今天我又向前邁步了一大步 第一次翻譯原文書讓我的成就感很大
也能讓我從中學習到很多知識 我相信我會越來越好

**Comment by s40723114** [comment]
倉儲網址:
https://s40723114.github.io/cad2019/content/w15%20First.html
影片連結:
https://youtu.be/f1X9VLfzXxA
心得:
在從學期初到現在,我學習到了很多繪圖套件的使用方法,還有WEBOT跟V-REP軟體之間的差異,也讓我知道了所謂的機械設計,也跟機電資有很大的關係,我知道自己還有很多不足的地方,但至少有在這門課學到一點東西,對於我未來再走機械這條路,還是有幫助的.

**Comment by s40723123** [comment]
倉儲提交連結
https://github.com/s40723123/cad2019/commit/cb0bc1e657222dc5dfd16d2ab6d4ae5ed9cfba5d
影片
https://www.youtube.com/watch?time_continue=109&v=CjGj1wZV0eI&feature=emb_title
我翻譯了NX12前言與第一章之內容讓我學到產品實現過程可以大致分為兩個階段：設計和製造。設計過程從識別新客戶需求和要設計的變量開始改進，由營銷人員從顧客。一旦收集了相關的設計信息，便制定了設計規範。進行可行性研究並提供相關設計信息以及詳細的設計和分析執行。從這些活動中獲得的結果的質量與分析的質量以及進行分析的工具。

**Comment by s40723147** [comment]
40723147 W15學習歷程與心得:
   在CAD2019課程當中接觸到更多的應用軟體:從NX12、inventor、 Solidworks、Solvespace......很多有關於繪圖的應用模擬分析，當中有很多是不曾學習過也不曾接觸過的在經歷15周後漸漸地接觸到更多不同的應用覺得相當的有趣，開始會尋找更多對自己有幫助的東西

**Comment by s40523113** [comment]
我的倉儲:https://s40523113.github.io/cad2019/content/w15.html
影片:https://www.youtube.com/watch?time_continue=4&v=XAsffwEU-8o&feature=emb_title
學習心得:
這學期的課程，有很多軟體和程式要去認識，而且還要與其他組員進行參與討論以及協同，我認為可以藉由這次的課程，來學到更多的軟體應用。

**Comment by s40523241** [comment]
無影片，之後會再努力

**Comment by s40723130** [comment]
影片:https://www.youtube.com/watch?v=KdZhPvu4VqY&feature=youtu.be
心得:
第一次翻原文書，雖然說沒有很複雜，但有很多NX內的工具名稱需要另外去找意思才有辦法知道名稱，這也花了我一點時間去對應它的中文，從中也讀到了一些未曾在NX中使用過的功能。

**Comment by s40723137** [comment]
倉儲連結：https://s40723137.github.io/cad2019/content/W15.html\
影片連結：https://www.youtube.com/watch?v=tIRh1ANbk5E

心得：在期末這段時間翻譯了NX12的基礎操作，讓我對NX12又更進一步的了解，也透過編譯可攜的NX12讓我可以使用的更便捷，也經過零件繪圖更加熟悉功能，雖整體來說然有些東西還不太瞭解，但是還是透過這堂課學習到了許多。

**Comment by s40723134** [comment]
影片:無
心得:目前無進度,之後會再努力

**Comment by s40723119** [comment]
倉儲:https://s40723119.github.io/cad2019/content/week15.html
影片:https://www.youtube.com/watch?v=-aszKoGwNVo&feature=youtu.be
心得:陸續學了solvespace、webots、v-rep等程式，且nx也從原本的後處理認識了繪圖，跟solidworks的繪圖方始也不相同，讓我可以在後處理的同時可以一邊繪圖

**Comment by s40723112** [comment]
倉儲提交連結:
https://github.com/s40723112/cad2019/commits/master
影片:
https://www.youtube.com/watch?v=nYxOM707zXc

心得:
這學期所學的東西幾乎都是在一年級所學的基礎的延伸，知道了如何使用github來執行團隊項目，來達到共同維護一個專案的目的，以訓練自己未來如何運用本課程所學到的跟社會上的人交流。

**Comment by s40723108** [comment]
倉儲網址
https://s40723108.github.io/cad2019/content/index.html
影片:卡99%來不及傳上去
學習心得:
本學期讓我學到很多曾為接觸的東西，受益良多阿

**Comment by s40723124** [comment]
倉儲網址:https://github.com/s40723124/cad2019
影片網址:https://www.youtube.com/watch?v=1YW1aHTTZ0I
心得:從第12周開始每周都在翻譯原文書，在翻譯的過程中也可以學習到如何使用NX，現在才翻譯一小部分而已，希望之後整本翻譯完，可以更了解如何使用NX，並對之後出社會有幫助。

**Comment by s40723141** [comment]
倉儲網址
https://github.com/s40723141/cad2019
影片
https://www.youtube.com/watch?v=AyU-sNQ_zfw&feature=youtu.be
學習心得:
這學期的課程需要非常認真，光是編譯solvespace只要一個步驟出錯找問題就必須花上很久的時間，更何況還有v-rep與webot等其他軟體的操作

**Comment by s40723122** [comment]
影片連結:https://www.youtube.com/watch?v=3ppnNWs44Rc
心得:以往沒有翻譯原文書的經驗，因為這個課才有機會接觸到翻譯原文書，也在翻譯Webots當中學到了一些Webots的技巧

**Comment by s40723138** [comment]
倉儲網址:https://github.com/s40723138/cad2019
影片連結:https://youtu.be/NkrWHnUszCg
學習心得:
了解到繪製的零件終於可以變成可以動的機械

**Comment by s40723142** [comment]
個人心得:
在學期開始後，我認識到了幾套軟體，solvespace、webots、V-rep和NX12等等，雖然我對這些一竅不通但透過組員所拍的影片及簡報，我漸漸的會了solvespace及NX12的繪圖，也學會了一點V-rep的操作，真的學刀了很多，希望學期結束前可以完成webots的操作
個人倉儲 https://s40723142.github.io/cad2019/content/index.html
影片 https://www.youtube.com/watch?v=41dY4GthQz0

**Comment by s40723104** [comment]
倉儲網址:
https://github.com/s40723104/cad2019
影片
https://www.youtube.com/watch?v=JS2xyYXY4Sc&feature=youtu.be
心得:
翻譯了NX12的基礎操作原文書，讓我更加了解NX12的使用，雖然還沒完全翻完，但翻了這一小部分，已經讓我學到很多，希望對我以後有很多不同的幫助。

**Comment by s40723107** [comment]
影片 :
https://www.youtube.com/watch?v=4EuBr2a4uEQ
我的倉儲 : 
https://github.com/s40723107/cad2019
心得: 
更加了解了NX12的由來以及操作方式 學習到solvespace、webots、v-rep等程式 了解了許多程式相關的內容，以及如何去進行繪圖

**Comment by s40623123** [comment]
影片鏈結:https://youtu.be/RtTk2fzkx4k
心得：用Solvespace繪製機械零件,跟其他繪圖軟體有很多不同的體驗

**Comment by s40723118** [comment]
倉儲網站
https://s40723118.github.io/cad2019/content/index.html
影片
https://www.youtube.com/watch?v=USOFiTmORDk&feature=youtu.be
心得:在這幾週努力完成組長給的任務；由於在家都是使用FFmpeg的Windows版，以至於在學校字幕打完無法合併，會在於之後補上

**Comment by 40723153** [comment]
倉儲: https://github.com/40723153/cad2019
影片: https://youtu.be/PpFLan0LvQQ
從學期初到現在循序漸進的學了許多不同的東西
從建立編輯網頁道不同程式的編譯和使用
除了繪圖還有模擬的程式
我這週做了分組的翻譯任務,更加了解了NX12的各種不同功用和操作方法
但在推送和更新的步驟還有很多不熟悉的地方需要麻煩別人教導
自己需要更努力跟上大家的進度

**Comment by s40723101** [comment]
學習心得:雖然已經有翻譯了Webots的原文書，但還不太會使用，繼續努力把影片拍出來，加油!!!

**Comment by s40723120** [comment]
倉儲網址: https://s40723120.github.io/cad2019/content/index.html
影片連結: https://www.youtube.com/watch?v=wyr0dr1gnCI
這幾周學到很多新的繪圖軟體、雖然每套軟體的主要功能大不相同，可是NX12和Solvespace繪圖功能有夠難用。希望以後可以再用這些軟體的時候可以得心應手一些

**Comment by s40723111** [comment]
倉儲https://github.com/s40723111/cad2019
影片:https://www.youtube.com/watch?v=PgA1At_zcDo
學習心得:
在學期開始後，我認識到solvespace、NX12這些軟體的操作， 我翻譯了NX12的電子書，以及了解到許多程式相關的內容，但還有很多不太懂的地方需要別人的教導，距離學習結束還有一些時間，式著努力趕上其他人

**Comment by s40723136** [comment]
倉儲連結:https://github.com/s40723136/cad2019ag1
影片:無
心得:倉儲僅有follow同組通學的推送，影片也拿不出東西，對於webots的學習進度也異常緩慢v rep學習尚未深入，nx繪製零件雖看著教程還是不會導入webots與v rep無法做到結合，整體來說學習成效不佳還需努力

**Comment by s40723132** [comment]
倉儲網址:https://github.com/s40723132/cad2019
影片:https://www.youtube.com/watch?v=DfauuhuP1N0
學習心得:這學期學習到的新的軟體NX12.Solvespace 用於繪圖感覺還是比不過業界常用的solidworks

**Comment by s40723111** [comment]
倉儲:https://github.com/s40723111/cad2019
影片:https://www.youtube.com/watch?v=PgA1At_zcDo
學習心得:
在學期開始後，我認識到solvespace、NX12這些軟體的操作， 我翻譯了NX12的電子書，以及了解到許多程式相關的內容，但還有很多不太懂的地方需要別人的教導，距離學習結束還有一些時間，式著努力趕上其他人

**Comment by s40723154** [comment]
心得: 雖然我很多東西都不會 不過我會在剩下的幾個星期中更努力學習

**Comment by s40723152** [comment]
倉儲連結:https://github.com/s40723152/cad2019
影片連結:無
學習心得: 這學期的電腦輔助工程實習，學習到了很多電腦軟體相關資訊，也是第一次觸碰到這些資訊，所以有些資訊還不太熟悉，但在接下來的這幾周內，我會陸續的學習，並且熟悉課程，並達到老師所期待的標準。

**Comment by s40723126** [comment]
影片:https://www.youtube.com/watch?v=omxQhYxpUKk&feature=youtu.be
心得: 
第一次翻譯原文書,很多單字都不知道需要花很長一段時間才翻譯完成
還學到nx12,solvespace這些軟件的操作 學習結束還有一些時間，會試著努力趕上其他人

**Comment by s40723155** [comment]
倉儲網址：https://github.com/s40723155/cad2019
影片：無
心得：這學期學了很多的軟體像是solvespace、webots、v-rep等程式，我第一次接觸這個課程，因此學的不是相當的ok，但是在接下來的時間內，我會更加努力的學習，把該做的事情做好!

**Comment by s40723115** [comment]
40723115
https://www.youtube.com/watch?v=BKq5CWgE5Iw&feature=youtu.be
https://s40723115.github.io/cad2019ag1/content/index.html
學習心得
知道協同對工作重要

**Comment by s40723110** [comment]
倉儲連結 https://s40723110.github.io/cad2019/content/index.html
影片連結 https://www.youtube.com/watch?v=SrgJ7tl7Vj4&t=21s
目前心得 : 透過這幾周的小組協同，了解了大致課堂上的教程走向以及目的，小組給予我的工作大多數都有在進行，不過因為需要去消化資訊的有點多，所以目前還在調整自己的速度。

**Comment by s40723146** [comment]
倉儲:https://github.com/s40723146/cad2019
影片:無
利用NX繪製零組件及翻譯應力分析部分，很好玩

**Comment by s40723150** [comment]
倉儲網址:https://s40723150.github.io/cad2019/
影片連結:尚未上傳，會補在倉儲
學習心得:學會了ipv6下用ssh推送資料，設定webots的配置，編譯solvespace等，這學期學到了很多軟體的應用，以後會漸漸上手的~還須要更努力

**Comment by s40723146** [comment]
倉儲:https://github.com/s40723146/cad2019
影片:無
利用NX繪製零組件及翻譯應力分析部分

**Comment by s40723144** [comment]
倉儲連結:https://127.0.0.1:9443/get_page/About
NX12第八章翻譯

**Comment by s40723102** [comment]
40723102
https://youtu.be/Nrn4rwxURxU
https://github.com/s40723102/cad2019/commits/master
心得:個人待加強

**Comment by s40723148** [comment]
倉儲:https://github.com/s40723148/cad2019
影片
Webots有點難

**Comment by s40723144** [comment]
倉儲連結:https://github.com/s40723144/cad2019/commits/master
第八章NX12翻譯
