### ISSUE TITLE
W15 2b 學員個人學習成果回報考試

### ISSUE THREAD

**Issue by mdecourse** [mdecourse/cad2019#33]
# W15 2b 查驗

請 2b 每位學員在 16:00 之前, 錄製一個至多 3 分鐘帶說明字幕的影片, 說明至今與本課程相關, 所完成的重要內容, 完成後將影片上傳至個人 Youtube 帳號下, 嵌入個人 W15 網頁後, 將倉儲提交連結與影片連結放入下列回應區, 並在回應區寫上個人詳細學習心得.

**Comment by s40723221** [comment]
倉儲提交連結:
https://github.com/s40723221/cad2019/commits/master
第15周個人網站連結:
https://s40723221.github.io/cad2019/content/week15-18.html
youtube影片連結:
https://youtu.be/vVTdUxYv_Qg
心得:
在這幾周我學到了自己編譯solvespaces繪圖軟體，操控模擬軟體webots和v-rep和繪圖軟體nx12等軟體，雖然要適應新的軟體很難但是我還是盡量的依靠電子書和網路上的教程達到了，在一開始使用webots時非常辛苦，必須去尋找物件設定的節點和如何在軟體裡面建模、實體的放置、受力的設定、物件碰撞之後的表現、用軟體去控制模型的方式，在v-rep也是如此，而且v-rep更加的困難，他的建模方式並沒有像webots一樣設定好所以使用起來困難重重，但是它的應用上的彈性是比較大的，希望在之後可以從這兩套軟體中分別找出對我們比較優勢的地方並且把它給發揮並且統整起來用做對物件模擬更加好用的工具或選項。

**Comment by s40723247** [comment]
倉儲提交連結 : https://github.com/s40723247/cad2019/commits/master

個人 W15 網頁連結 : https://s40723247.github.io/cad2019/content/week15-18.html

影片 : https://www.youtube.com/watch?v=cMUB-iczaNg&feature=youtu.be

心得˙: 期中考過後開始了分組的協同，並且組長也開始分配了分組網站的內容給大家，我被分配到的是proe的起源以及NX12電子書CH3的彙整等等.. ，協同分組網站之餘還要練習webot tutorial的內容，雖然自己很不會使用webot，但是參考了組長及其他同學的影片後，一步一步地慢慢做出來，其實還蠻有成就感的 ! 希望之後能夠再更好。

**Comment by s40723238** [comment]
倉儲提交連結:https://github.com/s40723238/cad2019/commits/master

個人W15網頁連結:https://s40723238.github.io/cad2019/content/week15-18.html

影片:https://www.youtube.com/watch?v=8cipJECIQa4

心得:再碰到ssh的難關的時候我是非常難過的，幸好有同學的幫助，我的ssh才能順利進行，真是太感謝了。希望以後碰到問題都有人可以問。

**Comment by s40723213** [comment]
影片:https://www.youtube.com/watch?v=su413LRlTi4&list=UU5SDOqSnuKGLgsWSdmdjDjw&index=1
倉儲:https://github.com/s40723213/cad2019
W15網站:https://s40723213.github.io/cad2019/content/Week15-18.html
心得:老師對不起，我不上進，進度嚴重落後，在此向您道歉，日後必定補上進度。哈們

**Comment by s40723232** [comment]
倉儲提交連結 : https://github.com/s40723232/cad2019/commits/master

個人 W15 網頁連結 :https://s40723232.github.io/cad2019/content/WEEK15.html

W15影片：https://www.youtube.com/watch?v=BesNm_29vPU

心得：
這幾週看了很多軟體的歷史，覺得很有趣，這些軟體在以後的學習路上都會用到，這次的翻譯有學到很多英文，很棒。

**Comment by s40723204** [comment]
倉儲 : https://github.com/s40723204/cad2019
影片 : https://youtu.be/zOHPHDy__Lc
心得 : 期中考後進行亂數分組，選出組長後由組長創建各分組倉儲，由於倉儲是隸屬在組長的帳號下，因此組員要利用FORK加入組長所創建的倉儲才可以參與分組網站。但組員不能直接 git push到分組倉儲去，要在push後到分組倉儲新增 pull request然後由組長同意後才能成功push。分組作業考驗的是同一個網站有許多人在編輯容易爆掉，此時要如何修復及維護分組網站就要由各組的成員一起解決。因為組員是利用fork參與分組倉儲的，要如何正向 pull request到分組倉儲，與組長倉儲commit差異過多時要如何反向 pull request組長的倉儲又是一個考驗。

**Comment by s40723205** [comment]
倉儲提交連結:
https://github.com/s40723205/cad2019
影片連結:
https://www.youtube.com/watch?v=ErGymhqusPA&feature=emb_title
第十五周個人網站連結:
https://s40723205.github.io/cad2019/content/Week15.html

心得:
這堂課讓我學習到一些關於python的程式，還有這學期新學到的Solvespace畫圖程式，學習到畫圖也可以使用程式來畫圖，不一定只有INVENTOR或solidworks這幾種選擇，還學到了nx12這個繪圖軟體也很值得學習，還有操控模擬的webots和v-rep這些都可以幫這我們畫圖使的繪畫出來的臨檢可以使用方便。讓大家是用分組的方式完成作業，可以讓強者多幫助弱者。

**Comment by s40723234** [comment]
倉儲連結: https://github.com/s40723234/cad2019
影片連結: https://youtu.be/XNjyjBDWteU
第15週個人網站連結:https://s40723234.github.io/cad2019/content/week15-18.html
心得   學習是一個很漫長的事，在這堂課我們學了vrep/slovespace/webots等軟體，很痛苦很開心， 
          而期中考後的內容是我影片的核心主題，期中考前的內容都是個人的努力決定個人的分數，期 
          中考後的協作變得不一樣，你個人的不努力或亂努力會影響小組的運作和進行，我很幸運遇到 
          一  個好組別，他們很給力，不會的部分會教我們，謝謝老師、組員們還有那些不是我們組卻願 
          意 幫助我們組的朋友們，例如承澤與正宇。

**Comment by s40723223** [comment]
倉儲連結:https://github.com/s40723223/cad2019
個人 W15 網頁連結 : https://s40723223.github.io/cad2019/content/Week15~18.html
影片連結:https://www.youtube.com/watch?v=vtm3Jx104-4&feature=youtu.be
心得:到現在15周我在webots和v-rep和nx12等軟體上遇到了許多不懂的東西以及一些問題，但藉著同學的幫助，讓我知道如何操作，雖然還有不會的地方，但我會努力去學，並且希望在未來可以運用到

**Comment by s40723239** [comment]
倉儲連結:
https://github.com/s40723239/cad2019
地15週個人網站連結:
https://s40723239.github.io/cad2019/content/Week15~Week18.html
YT影片連結:
https://youtu.be/Ax4Wkw_jcnU

心得:練習WEBOTS是滿有趣的，雖然某些章節步驟較複雜，但網站上的教學步驟都很清楚，也很感謝第3組的組員在我有困難時可以幫助我。

**Comment by s40723246** [comment]
倉儲繳交連結:https://s40723246.github.io/cad2019/content/index.html
影片:https://youtu.be/VCCIsJUSYXw
W15:https://s40723246.github.io/cad2019/content/week15~18.html
學習心得:最近一直在研究webot的操作，從思考上的模擬到，有了隨身上的模擬系統，在於我們使用上面更加方便，我也跟著簡報上面的步驟學習，對於webot這個模擬系統又更加了解，有這自己建造的world，看起來真的是很有成就感，跟著老師的教材，也了解了很多模擬系統的資料，原本對於PROE完全不了解的我，也已經有點東西了，日後還會繼續做一些額外的webot，學習感倍分。

**Comment by s40723249** [comment]
倉儲連結 : https://github.com/s40723249/cad2019/commits/master

個人W15網頁連結 : https://s40723249.github.io/cad2019/content/week15.html

影片連結 : https://www.youtube.com/watch?v=_MMMvJpFg5Y

心得:一開始使用solvespace的時候蠻喜歡的，不只小又方便隨身碟可攜帶。期中考後開始使用webot，與之前的大有不同，老師讓我們漸漸接觸協同設計這塊，並讓我們自己慢慢熟悉並打基礎，之後開始小組工作，先是翻譯電子書，在一起做webot但我不太熟悉，需要慢慢學習，希望之後也能得心應手，詢問同學及組員意見就能慢慢適應!

**Comment by s40723244** [comment]
倉儲提交連結 : `https://github.com/s40723244/cad2019/commits/master`

個人 W15 網頁連結 : `https://s40723244.github.io/cad2019/content/week15.html`

影片 : `https://youtu.be/6vgdobes59U`

心得˙: 期中考之前的進度有跟上，可是期中考之後發現越來越難搞了，沒辦法只好慢慢來，導致進度落後，後續會再努力補上影片及倉儲內容，已完成個人的程式設計課程，另外對於webot的模擬以及NX的操作個人還不太行，後續會努力練習的。

**Comment by s40723210** [comment]
倉儲提交連結:
https://github.com/s40723210/cad2019/commits/master
第15周個人網站連結:
https://s40723210.github.io/cad2019/content/Week15-18.html
youtube影片連結:
https://youtu.be/zStI_0WxzIM
心得:

**Comment by s40723219** [comment]
倉儲 :https://github.com/s40723219/cad2019

個人網址 :https://s40723219.github.io/cad2019/content/index.html

影片 :https://www.youtube.com/watch?v=gzKZN95KYm8&feature=youtu.be

心得 :在進行分組管理倉儲後，除了要注意不要與組員衝突，還有事組章分配下來的工作，以及老師要求的webots soildwork NX等，而在經過編譯其中的原文書後也對cad等製圖軟體有更深的了解，而webots的操作在日後也可以駕輕就熟。

**Comment by s40723241** [comment]
個人網站  :  https://s40723241.github.io/cad2019/content/index.html
倉儲  :  https://github.com/s40723241/cad2019/commits/master
影片  :  https://youtu.be/TPkK6M45olU
心得  :  從學期開始到現在，從對程式一竅不通到現在可以自己一個人更新網站 ，我覺得對我來說真的是十分的不容易，原本我是對程式這類東西十分陌生且畏懼的，但經過這學期的課程之後，我發現其實好像是我自己在嚇自己，程式這個東西如果好好學真的會是對未來十分有幫助的一項工具呢!!

**Comment by s40723203** [comment]
倉儲: https://github.com/s40723203/cad2019/commits/master
網站: https://s40723203.github.io/cad2019/content/week15-18.html
影片: https://youtu.be/EDuEneB8VsM
心得: 學了很多以前不知道或是沒聽過的事物，覺得新奇。不再覺得電腦無趣，其實他可以很不一樣。
到目前為止學到了Solvespace、NX、Webots和V-rep等，一開始覺得不能接受到現在的順手，都讓人覺得是在進步的。
翻譯並節錄重點也是，學到了不只英文能力和重點整理，還能更加理解程式該如何操作。

**Comment by s40723240** [comment]
倉儲提交連結:https://github.com/s40723240/cad2019/commits/master
第15周個人網站連結:https://s40723240.github.io/cad2019/content/Week15-18.html
youtube影片連結:https://www.youtube.com/watch?v=riwvZlpWW2M&feature=emb_logo

心得:這學期課程學習了利用solvespace和NX來繪製零件及差別，還有練習webots和v-rep的操作，這門課讓我學習到了很多東西，其中細節需要親手去操作才會體會，solvespace容量小適合簡單繪製；nx12需要相當熟悉畫圖功能和介面才能操作，容量當然也很大。webots場景比v-rep還逼真，且操作也比v-rep略為簡易，但v-rep功能非常的多，零件功能非常的細，兩者各有長處。

**Comment by s40723242** [comment]
倉儲提交連結 :https://github.com/s40723242/cad2019/commits/master

個人 W15 網頁連結 :https://s40723242.github.io/cad2019/content/week15-18.html

影片 : https://www.youtube.com/watch?v=YSm6I95JHPw&feature=emb_title

心得˙:在與組員協同後，雖然在一開始會有許多技術上的落差及衝突，但在各組員及老師的催促下，也漸漸地跟上腳步，當我們在整理solidwork、nx及cero後除了更加了解軟件的來歷也更了解他是如何使用，在13周後開始接觸Webots及Vrep，或許是剛開始不太熟悉做得有些痛苦，任何東西都必須從0開始，Vrep更是如此，但透過Webots及Vrep的教學網站慢慢一點的練習，也漸漸的克服困難，希望能把這兩套軟件學好，讓未來能有更好的工具能夠使用。

**Comment by s40723243** [comment]
倉儲:https://github.com/s40723243/cad2019
影片:https://www.youtube.com/watch?v=eT-i_oYouj4&feature=youtu.be
第15週個人網站連結:https://s40723243.github.io/cad2019/content/week15-18.html
https://s40723243.github.io/cad2019/content/week15-18.html
心得:經過這幾週的練習，我學到了一點東西，雖然不是很多，但還是比一年級更認真了，也覺得Webot做的東西非常有趣，也練習了NX與Solidworks這兩款製圖軟體，並且在翻譯原文書的過程中，也稍微的練習了一下英文，並且也深知英文對我們這個科系的重要。

**Comment by s40723245** [comment]
倉儲提交連結:https://github.com/s40723245/cad2019/commits/master
第15周個人網站連結:https://s40723245.github.io/cad2019/content/week15-18.html
youtube影片連結:https://www.youtube.com/watch?v=9RxsQPFrlzk&feature=youtu.be
心得：在這學期我學到了許多東西，從一開始solidworks的繪圖到現在webots tutorial操作，要看懂NX原文書花了很多時間，不過持之以恆到最後我相信一定會有所成果。雖然我的進度比較慢，不過會慢慢跟上進度的。

**Comment by s40723237** [comment]
倉儲提交連結 :https://github.com/s40723237/cad2019
影片:https://youtu.be/0_W8dkp33pg
心得 : 期中考之前的進度都有跟上 ，11週之後開始由組長分配工作，一起完成小組網頁的各週任務。

**Comment by s40723216** [comment]
倉儲連結:https://s40723216.github.io/cad2019/content/index.html
心得:雖然現在對python還不是很熟，但還是看著同學拍的影片一步步跟著做，這次開始小組的任務後變得比較需要分工合作，不像以前能一直偷懶，我也盡量透過看別人的影片來努力補齊進度，並且有上youtube查詢NX12的操作畫法來提升對NX的熟練度。

**Comment by s40739214** [comment]
影片連結:https://youtu.be/JLSiyZbzu7c
心得:因為有換筆電，所以有些東西尚未準備齊全導致今天有些東西無法順利完成，之後會再進行補繳的動作。第十週之後的進度是分組一起進行的，過程一起分工合作，讓組員之間可以更順利完成作業。有些東西是之前沒有學過的，透過這個課程了解到其他軟體，相信努力學習之後可以學以致用。

**Comment by s40723227** [comment]
倉儲提交連結:
https://github.com/s40723227/cad2019/commits/master
第15周個人網站連結:
https://s40723227.github.io/cad2019/content/Week15~Week18.html
youtube影片連結:
https://www.youtube.com/watch?v=N9OyG7pRzQI&feature=youtu.be
心得:
在這幾周，我了解很多關於各繪圖軟體的發展及用途.優缺點，在NX的部分，練習很多2D草圖的繪製，其中包含一些曲線輪廓要如何繪製.幾何特徵如何設定，使我在NX繪圖更加的了解。在模擬程式方面用了Webots.Vrep，從繪製零件到參數設定，了解到要模擬程式是多麼困難，但在這幾周的例題練習，也讓我了解了這兩個模擬程式許多。

**Comment by s40723228** [comment]
簽到
心得:進度還在趕。

**Comment by s40723207** [comment]
15週連接https://s40723207.github.io/cad2019/content/Week15~Week18.html

**Comment by s40723233** [comment]
倉儲提交連結:https://github.com/s40723233/cad2019/commits/master
第15周個人網站連結:https://s40723233.github.io/cad2019/content/Week15~18.html
影片連結:https://www.youtube.com/watch?v=yt0tGqDGZso
心得:在這學期我學到了許多東西，當我們在學習solidwork及各繪圖軟體的發展及用途，對我來說真的是十分的不容易
但是我還是會努力學習，爭取學會熟練這些軟體

**Comment by s40723250** [comment]
倉儲:https://s40723250.github.io/cad2019/content/Week13~15.html
影片:https://www.youtube.com/watch?v=o8BIe7BWQyw&feature=youtu.be
心得:雖然這幾周,有很多東西不懂,但在小組的成員的幫助下,都克服了,所以很感謝小組的大家

**Comment by s40723123** [comment]
https://youtu.be/FgluoI3wZ7I

**Comment by s40723209** [comment]
倉儲:https://github.com/s40723209/cad2019
第15周個人網站連結:https://s40723209.github.io/cad2019/content/week15~18.html
影片;https://www.youtube.com/watch?v=8RFNCPmVTB4&t=1s
心得:進度落後一點點，但我會努力學習趕快補上的

**Comment by s40723212** [comment]
網誌:https://s40723212.github.io/cad2019/content/index.html
倉儲:https://github.com/s40723212/cad2019
影片:https://www.youtube.com/watch?v=SJsyuWkG8KI
心得:原文書真的有夠難讀，英文語法架構跟中文真的差很多，花了好多時間才大概讀懂書裡想表達甚麼，看了原文書才知道中譯本偷了好多東西，很多東西只是簡略帶過，真的要懂其中原理必須看原文書。

**Comment by s40723229** [comment]
倉儲:https://s40723229.github.io/cad2019/content/index.html
影片來不及製作完成
心得:現在的進度正在把webots的練習完成。

**Comment by s40723206** [comment]
倉儲:https://github.com/s40723206/cad2019
第15周個人網站連結:https://s40723206.github.io/cad2019/content/week15-18.html
影片:https://youtu.be/FgluoI3wZ7I
心得:進度有點落後，vrep還沒摸索完，我會努力補上。這幾周也謝謝組員努力

**Comment by s40723222** [comment]
影片:https://www.youtube.com/watch?v=d1K260IqsMI
心得:進度大落後，我會努力加油補上的，十分抱歉。也非常感謝隊友對我的幫忙，謝謝他們。
