### ISSUE TITLE
W16 2a 越野車零組件設計繪圖查驗

### ISSUE THREAD

**Issue by mdecourse** [mdecourse/cad2019#34]
# W16 2a cad 練習

請注意: 只有在 12/27 (五) 09:30-12:00 製作的影片與倉儲所提交的內容納入計分

請 2a 各學員根據 [Task2](http://mde.tw/cad2019/content/Task2.html) 中 [Onshpae 越野車零組件](https://cad.onshape.com/documents/0c757e42f113318abade702c/w/83a3818a1aef5d4234265d9c/e/0284daee1c8866acdbcf0b9d)之尺寸與配置, 利用 Solvespace 完成簡化後的越野車零組件設計繪圖.

完成後請將所有零組件檔案, 放入個人倉儲 downloads 目錄中的 solvespace 子目錄, 然後將越野車組立件, 以 STL 格式轉出後, 轉入 V-rep 後, 將 ttt 檔案放入個人倉儲 downloads 目錄中的 solvespace 子目錄.

並將越野車組立件, 以 WRL 格式轉出後, 轉入 Webots 後, 將 wbt 檔案放入個人倉儲 downloads 目錄中的 solvespace 子目錄.

完成上述查驗任務後, 請將簡要過程拍成至多 3 分鐘的帶說明字幕導覽影片, 並將影片嵌入 W16 查驗頁面後, 將提交連結, 頁面連結與影片連結放入下列回應中, 附上操作心得, 並針對所碰到的問題進行說明討論.

**Comment by s40623252** [comment]
心得：老師不好意思雖然我沒做出來 但我想大四如果您有開一年級的選修我很願意再去多學習一些比較基礎的內容 也謝謝您這學期認真的教導

https://www.youtube.com/channel/UCF9wJf90CR83I80UG_F8FZQ

**Comment by 40823138** [comment]
心得:這禮拜的小考好難啊，因為我都把V-rep 、webots 操作都丟給隊友去做導致我都不會，看來我要多認真學習，不要在分配工作了。
https://www.youtube.com/watch?v=dQNpUu72Xac

**Comment by s40723125** [comment]
心得:這禮拜的小考好難啊，因為我都把V-rep 、webots 操作都丟給隊友去做導致我都不會，看來我要多認真學習，不要在分配工作了。
https://www.youtube.com/watch?v=dQNpUu72Xac&t=1s

**Comment by s40723103** [comment]
心得: 在一開始畫零件時腦袋一片空白，當下知道要考試有點慌張，而後又遇到指令的問題，這過程中與時間賽跑出充滿緊張與刺激感，最耨終於把成品做出，雖然圖文不符感到很抱歉，但在時間有限的課程裡，這是我盡量做出的成果，也了解匯出的應用是多麼重要的部分。

影片: https://youtu.be/deyuv227R-M
倉儲紀錄: https://github.com/s40723103/cad2019/commits/master
網頁: https://s40723103.github.io/cad2019/content/Week16.html

**Comment by s40723124** [comment]
心得:因為還在慢慢學習中，所以覺得這次的小考特別難，加上時間沒有把握好，沒有完整的做出來，但我已經盡力了。希望到學期末之前可以把這學期老師教的所有東西用熟。
影片:https://www.youtube.com/watch?v=vn6i09zeorY
倉儲:https://github.com/s40723124/cad2019
網站:https://s40723124.github.io/cad2019/content/index.html

**Comment by s40723147** [comment]
提交連結:https://github.com/s40723147/cad2019/commits/master

頁面連結:https://s40723147.github.io/cad2019/content/W16.html

影片連結:https://youtu.be/G9QywEhOCDc

學習心得: 剛看到題目的時候覺得非常困難，困難的部分是在solvespace 繪圖上沒那麼上手起初以為會製作不完嘗試過很多方法想要繪製更多零組件裝配，但是碰到裝配的問題還是無法順利進行這是我在這次考試'當中遇到最困難的問題‧這裡也浮現出平時努力不夠的問題，往後會更加努力!!

**Comment by s40723119** [comment]
心得:不能只專一某些東西，而是要各方面顧到，這樣在組件的時候才不會遇到問題
影片:https://www.youtube.com/watch?v=C0Yeo1JUziA
倉儲:https://s40723119.github.io/cad2019/content/week16.html

**Comment by s40723152** [comment]
心得:今天考試內容雖然我還不太熟悉，導致今天遇到的難題非常多，也無法達成老師所要的標準，但是在期末考前我會繼續努力學習，並在期末之前把這學期所學的東西好好地再複習一次，並達成老師所要的期許。
影片:https://www.youtube.com/watch?v=kEE0Srb67Y0
個人倉儲:https://github.com/s40723152/cad2019
網站:https://s40723152.github.io/cad2019/content/index.html

**Comment by s40723149** [comment]
心得:看到Onshape上的越野車剛開始覺得很複雜，但是自己嘗試著用solvespace簡化他，發現要從頭開始設計一個機構其實並不是想像中那麼簡單，也發現自己的努力還不夠，必須多加努力。
影片:https://www.youtube.com/watch?v=ei8pZRGKlmw

**Comment by s40723123** [comment]
心得:這次考試讓我發現組合零件約束的操作我不太熟，下次再努力，webot的部分還不太熟也是之後會努力。
影片:https://www.youtube.com/watch?v=HaqPfHkHT1o
提交連結:https://github.com/s40723123/cad2019/commits/master
倉儲:https://github.com/s40723123/cad2019

**Comment by s40723115** [comment]
40723115
倉儲:https://s40723115.github.io/cad2019/content/index.html
影片:https://www.youtube.com/watch?v=tVzFpDyrwx8&feature=youtu.be
github:https://github.com/s40723115/cad2019
心得:一開始畫腦袋一片空白，但最後還是擠出了一點東西，還發現v-rep讀不到線條只能讀立體的物件
希望在期末考前能把老師給我們 的軟體熟悉，往後會更努力。

**Comment by s40723155** [comment]
心得： 根據越野車零組件尺寸，利用 solvespace初步畫出越野車的零件，我只畫出部分的零件而已，在有限的時間裡，盡我最大的努力畫出來了，希望之後也能夠把它給完成好，在之後的時間裡繼續努力。
影片：https://www.youtube.com/watch?v=eRwwisF5ck0
網頁：https://s40723155.github.io/cad2019/content/index.html
個人倉儲：https://github.com/s40723155/cad2019

**Comment by s40723137** [comment]
心得：這禮拜畫越野車實在有點困難，知道是考試後有點緊張，因為遇到程式的一些BUG導致材料長出錯誤，還有技巧有些生疏，畫到現在才剛組完車子，所以來不及拍影片

倉儲：https://s40723137.github.io/cad2019/content/solvespace.html

**Comment by s40723114** [comment]
心得: 在這次的查驗,知道自己許多的不足,還離機械設計有一段距離,但能夠成功地把畫的零件轉入V-REP,也是一個不錯的學習,webot不太熟,往後會更努力的學習
影片: https://youtu.be/fvFu9G8E3wo
倉儲紀錄: https://github.com/s40723114/cad2019/commits/master
網頁: https://s40723114.github.io/cad2019/content/w16%20second.html

**Comment by 40723153** [comment]
心得:本週的考試應用到了很多不同軟體,但我只完成了solvespace的繪圖也畫得不是很好,很多同學都完成轉檔並即時的繳交,對此深感到自己學習的不足,希望在剩下的時間裡能夠努力跟上落後的進度達到及格的標準
影片:https://youtu.be/MRaJFg3fWgI
倉儲:https://github.com/40723153/cad2019
網站:https://40723153.github.io/cad2019/content/index.html

**Comment by s40723142** [comment]
心得；一開始畫的時候覺得很慌張，但是仔細想了一下後，運用之前所學的東西，還是完成了作業。
倉儲 https://github.com/s40723142/cad2019
影片 https://youtu.be/jD3D7DOXGFo

**Comment by s40723112** [comment]
心得:在畫的過程中腦袋一片空白，根本不知道如何下手，不過還是有畫出一點東西，希望可以在學期結束前把軟體都學習好。
倉儲:https://github.com/s40723112/cad2019
影片:https://www.youtube.com/watch?v=OBw_NQzfFXg

**Comment by s40523242** [comment]
心得:從一開始先思考要如何簡化,.到直行在到執行上遇到問題解決問體在最後的最後
        逐一的完成零件
         完成此成品後我更加熟悉此軟體
影片:https://youtu.be/6mYgp1wcnv4

**Comment by s40523241** [comment]
無影片，有繪製零件
謝謝老師這學期的教導
[github倉儲:](https://github.com/s40523241/cad2019/commits/master)

**Comment by 40823238** [comment]
心得：由於我的solvespace solvespace 有可以轉成wrl的選，我之後回去會從心再做一次
影片連結：https://youtu.be/TuqC8NBYWxc

**Comment by s40723101** [comment]
心得: 這禮拜的小考讓我知道自己不足的地方，題目雖然沒做出來，但我會再繼續努力的
https://www.youtube.com/watch?v=LIIusX8L_A8

**Comment by s40723118** [comment]
心得:這次小考太難，尤其在組合的部分，然後遇到了設備上的問題：滑鼠中鍵不靈感，會盡力補足沒畫完的部分及影片。
影片:https://youtu.be/Lmy0CBqRelY
倉儲:https://github.com/s40723118/cad2019
網站:https://s40723118.github.io/cad2019/content/index.html

**Comment by s40723141** [comment]
倉儲連結：https://github.com/s40723141/cad2019.git
影片網址：https://www.youtube.com/watch?v=O0IIgkMRTvM
心得：雖然有進行操作，但過程失誤百出，不太適合拍成影片，只有製作練習webot的基礎操作影片而已

**Comment by s40523113** [comment]
倉儲:https://github.com/s40523113/cad2019
網頁:https://s40523113.github.io/cad2019/content/w16.html
影片連結:https://www.youtube.com/watch?v=qAupiHYh1rg&feature=emb_title
心得:由於還沒對solvespace徹底的了解，所以在繪製過程中，花了很多時間在這上面，以後會再多去了解solvespace的應用。

**Comment by s40723110** [comment]
影片: https://youtu.be/n9lwilevRu8
個人倉儲 : https://s40723110.github.io/cad2019/content/index.html
心得 : 開始設計時感覺程式方面真的要再花點時間去了解快捷鍵(速度太慢)，同時構想也需要更快去執行。另外在轉檔時有些問題，讓我覺得更需要下點功夫學習

**Comment by s40723122** [comment]
心得:本周的考試畫圖畫不太出來，希望可以在學期末前學好
個人倉儲：https://github.com/s40723122/cad2019

**Comment by s40723102** [comment]
https://youtu.be/yPrNbR-sWNs
心得；獲益良多，我待加強

**Comment by s40723104** [comment]
心得:這次小考對內容不熟悉，導致來不及提交，也來不及完成影片，回去後會再多練習，再補上沒完成的進度
倉儲:https://github.com/s40723104/cad2019

**Comment by s40723130** [comment]
已經畫了一些零件，倉儲有些問題之後會把零件檔補上
倉儲:https://s40723130.github.io/cad2019/content/index.html
影片也會一起補上

**Comment by s40723145** [comment]
提交連結:https://github.com/s40723145/cad2019/commits/master
頁面連結:https://s40723145.github.io/cad2019/content/Week16.html
影片連結:https://youtu.be/m-8569qiqF0
心得:

**Comment by s40723107** [comment]
心得: 因為時間上把握不好，導致沒有畫完影片也來不及錄影 希望下次可以更把務握好時間
倉儲 :https://github.com/s40723107/cad2019
網站 :https://s40723107.github.io/cad2019/content/index.html

**Comment by s40723154** [comment]
心得: 雖然畫的不多 但是說真的我很開心 因為我原本是真的甚麼都部會 但自從上禮拜甚麼都拍不出來後 我深刻地體會到 這樣不行 不僅對不起老師在這邊花時間教我們 也沒辦法給我的組員一個交代 於是我開始認真學習  謝謝同學們願意這麼有耐心的花時間來教我 真的很感動 謝謝你們  而今天我也盡我所能用solvespacec畫圖並拍出一個影片
影片連結: https://www.youtube.com/watch?v=5h2TdyI1oOs
倉儲: https://github.com/s40723154/cad2019

**Comment by s40723144** [comment]
老師對不起我沒好好學會前面教的東西不過我這禮拜有努力的畫出一些東西(在倉儲的第16週)未來一周我會把今天的考試的任務補上在我的倉儲的第16週

倉儲:https://github.com/s40723144/cad2019
網誌:https://s40723144.github.io/cad2019/content/index.html

**Comment by s40723136** [comment]
40723136
倉儲:https://github.com/s40723136/cad2019
心得:這周也沒辦法拿出影片但能在倉儲上交出零件

**Comment by s40723148** [comment]
影片:https://www.youtube.com/channel/UCSEHMzQJcC2zslpQgoBFKuA?view_as=subscriber
倉儲:https://github.com/s40723148/cad2019/commits/master
心得:今天考試的題目只能做到solvespace
,webots和v-rep還在努力學習中

**Comment by s40723108** [comment]
心得:這次時間太快導致做不完影片丟倉儲沒時間上傳
https://s40723108.github.io/cad2019/content/index.html

**Comment by s40723138** [comment]
心得:對於solvespace不夠熟悉,在約束尚無法完成,成功大致上繪製但無法再webot與V-REP上打開
倉儲:https://github.com/s40723138/cad2019

**Comment by s40723132** [comment]
心得:這次小考讓我體認到不要只會靠別人去完成，自己也要實際去摸摸看
倉儲:https://github.com/s40723132/cad2019

**Comment by s40723126** [comment]
倉儲:https://github.com/s40723126/cad2019
心得:小考很難,都畫不出來

**Comment by s40723121** [comment]
心得:這次雖然我沒有成功畫出來，但是讓我知道這個軟體可以應用在設計車子上面\

**Comment by s40723134** [comment]
這周依舊沒做出成品,回去後多磨練
倉儲:https://github.com/s40723134/cad2019

**Comment by s40723150** [comment]
心得：由於我的solvespace solvespace 有可以轉成wrl的選，我之後回去會重新再做一次
影片連結：https://youtu.be/TuqC8NBYWxc

**Comment by s40723120** [comment]
心得:這次小考有點不太會，對於slovespaceslovespace還不是很順手，最後組裝完成時更改完路徑後，組裝好的車子就不見了，原本想要從心再組一次可是來不及了。
倉儲:

**Comment by s40723120** [comment]
心得:這次小考有點不太會，對於slovespaceslovespace還不是很順手，最後組裝完成時更改完路徑後，組裝好的車子就不見了，原本想要從心再組一次可是來不及了。
倉儲:

**Comment by s40723111** [comment]
心得:因為時間上把握不好所以沒能完成之後會把影片補上
倉儲:https://s40723111.github.io/cad2019/content/index.html
