### ISSUE TITLE
W16 2b 越野車零組件設計繪圖查驗

### ISSUE THREAD

**Issue by mdecourse** [mdecourse/cad2019#35]
# W16 2b cad 練習

請注意: 只有在 12/27 (五) 13:30-16:00 製作的影片與倉儲所提交的內容納入計分

請 2b 各學員根據 [Task2](http://mde.tw/cad2019/content/Task2.html) 中 [Onshpae 越野車零組件](https://cad.onshape.com/documents/0c757e42f113318abade702c/w/83a3818a1aef5d4234265d9c/e/0284daee1c8866acdbcf0b9d)之尺寸與配置, 利用 Solvespace 完成簡化後的越野車零組件設計繪圖.

完成後請將所有零組件檔案, 放入個人倉儲 downloads 目錄中的 solvespace 子目錄, 然後將越野車組立件, 以 STL 格式轉出後, 轉入 V-rep 後, 將 ttt 檔案放入個人倉儲 downloads 目錄中的 solvespace 子目錄.

並將越野車組立件, 以 WRL 格式轉出後, 轉入 Webots 後, 將 wbt 檔案放入個人倉儲 downloads 目錄中的 solvespace 子目錄.

完成上述查驗任務後, 請將簡要過程拍成至多 3 分鐘的帶說明字幕導覽影片, 並將影片嵌入 W16 查驗頁面後, 將提交連結, 頁面連結與影片連結放入下列回應中, 附上操作心得, 並針對所碰到的問題進行說明討論.

**Comment by s40723221** [comment]
心得:
繪製solvespace零件的部分可能是本次查驗比較困難的部分，還有組合和設計如何簡化機體等，這樣的設計對我們來說雖然非常的困難但也是必須去學習得一塊，轉出stl和wrl之後必須要導入webots和v-rep之中，若要真實的達到模擬，那必須要做更多的對程式修改，例如:solvespace切割檔案的機制或webots的驅動等，才能夠達到我們對連接軸的驅動和加入馬達達到輸出馬力的部分和分開切割零件的功能，這部分是本次查驗之中比較難的延伸部分，如果能夠對這部分深入並且達成，那會是比較值得去開發的一塊區域。

影片: https://www.youtube.com/watch?v=Kq4CeA0L3cc&feature=emb_title
commit紀錄: https://github.com/s40723221/cad2019/commits/master
網頁: https://s40723221.github.io/cad2019/content/week15-18.html

**Comment by s40723210** [comment]
倉儲提交連結:
https://github.com/s40723210/cad2019/commits/master
第16周個人網站連結:
https://s40723210.github.io/cad2019/content/Week15-18.html
youtube影片連結:
https://youtu.be/ZGVvMynspJI
心得:

**Comment by s40723241** [comment]
心得: 
這次使用Solvespace來畫越野車零件然後再將其組起來，接著轉檔，然後匯入V-rep。
這次測驗下來，我發現其實我對這些工具還不是很熟習，還需要再加把勁練習呢!!!!
影片: https://youtu.be/7Gz8n3h73js
commit紀錄: https://github.com/s40723241/cad2019/commits/master
網頁: https://s40723241.github.io/cad2019/content/week.html

**Comment by s40723218** [comment]
心得:
這次使solvespace繪製越野車零件便組裝，由於不是很熟練所以花了很多時間去繪圖，並且轉v-rep及webots，但是時間不夠所以沒做完，所以回去會加緊練習並補齊進度的!
網頁:https://s40723218.github.io/cad2019/content/index.html
影片:https://www.youtube.com/watch?v=NsDepbib9Ts&feature=youtu.be

**Comment by s40723240** [comment]
心得:經過一系列的操作後，發現自己對於solvespace到webots和v-rep的過程還是不熟練，但是還是有吸收經驗的感覺，知道自己不熟的地方在哪裡，要如何去改進..，希望經過一次又一次的練習後就能越來越熟悉這門課的核心了。
w16影片:https://www.youtube.com/watch?v=DW-Oy9KTczA&feature=youtu.be
commit紀錄:https://github.com/s40723240/cad2019/commits/master
網頁連結:https://s40723240.github.io/cad2019/content/Week15-18.html

**Comment by s40723249** [comment]
倉儲: https://github.com/s40723249/cad2019
網頁: https://s40723249.github.io/cad2019/content/index.html
影片: https://www.youtube.com/watch?v=p_q02QBF-DU
心得: 這次綜合做了SOLVESPACE跟V-REP跟WEBOT讓我們真正意識到自己的不熟練，希望下次能做得更好，回去更加努力練習。

**Comment by s40723213** [comment]
心得:這次的小考，要用solvespace畫出一台車子，然後轉檔成STL，再組裝起來丟到WEBOTS，但是時間上不夠，所以只畫出車子，雖然有點醜，請不要介意，後面的任務沒有做完，但是參考其他人的影片，我可以感覺得出來，不夠熟悉的我，估計是做不出來的。
影片:https://www.youtube.com/watch?v=myNxnQNvjyM
W16個人網站:https://s40723213.github.io/cad2019/content/Week15-18.html
倉儲:https://github.com/s40723213/cad2019/commits/master

**Comment by s40723205** [comment]
心得:因為這周的考察實在有點困難，所以我只有把圖畫出來組裝好而已，後面的動作，就都還沒有完成，我才發現原來我圖畫的速度真的需要加油。
網頁：https://s40723205.github.io/cad2019/content/Week15.html
影片:https://www.youtube.com/watch?v=sAyGyZbTKkk

**Comment by s40723219** [comment]
心得:在使用solvespace畫圖時還不太熟悉，因此會耗費較多時間在畫圖，而轉檔的部分則較無問題。
網頁 :https://s40723219.github.io/cad2019/content/index.html
影片:https://www.youtube.com/watch?v=JgG9F9drzMo&feature=youtu.be

**Comment by 40723153** [comment]
心得:
這次是用solvespacesolvespace來繪製越野車的各零件並組合起來放進webot來模擬，雖然我有把夠零件繪製出來，但當我USB插入電腦時發現某些檔案毀損了，因此無法將其導入v-rep和做後續的動作，雖然這次也沒有達到及格的標準，但我相信下次來的時候，我是已經做好及格的準備來考試。
網頁https://s40723216.github.io/cad2019/content/Week15~18.html

**Comment by s40723223** [comment]
心得:
在這次用solvespace畫車子，對我而言有點困難，但花了許多時間後終於完成了，讓我傭有了成就感，希望能夠越來越熟練。
影片:https://www.youtube.com/watch?v=J1XtdP4y508&feature=youtu.be
網站:https://s40723223.github.io/cad2019/content/Week15~18.html
倉儲:https://github.com/s40723223/cad2019/commits/master

**Comment by s40723232** [comment]
心得: 這周考是非常困難，在上課時間內要畫完這些東西不太可能，程式也出一堆問題，讓我非常頭痛。
網頁:https://s40723232.github.io/cad2019/content/index.html
影片:https://www.youtube.com/watch?v=mXtOxsCsIBQ&feature=youtu.be

**Comment by s40723203** [comment]
影片連結:https://youtu.be/RMaDeA4pyNs
倉儲:https://github.com/s40723203/cad2019/commits/master
網頁網址:https://s40723203.github.io/cad2019/content/week15-18.html
心得:
組裝車體和轉至vrep和webots時遇到了許多問題，很感謝同學的幫助讓我完成這次作業。不熟悉程式的我該檢討並開始學習應用了，相信之後會越來越好的。

**Comment by s40723239** [comment]
影片: https://youtu.be/rwK6VrkKXkU 
剛才在git push 的時候出現了一些問題，導致我只有放影片網址 
有一段時間沒有用solvespace畫圖了 這次把三個程式一起應用感覺很新奇 ，感謝我的組員幫助我

**Comment by s40723247** [comment]
心得:
現在到了第16週了，也慢慢接近尾聲，作業遠遠比以前的難很多，自己有些跟不上，也做不太好，所以只能照著同學的影片，一步一步慢慢來，雖然自己的程度不是很好，但是其實一步一步做後完成的那個成就感也是有的，所以希望之後能夠越來越好。

影片: https://youtu.be/47VepTkI5do
commit紀錄: https://github.com/s40723247/cad2019/commits/master
網頁: https://s40723247.github.io/cad2019/content/week15-18.html

**Comment by s40723207** [comment]
影片:https://youtu.be/2LTtnS_Lr6o
倉儲：https://s40723207.github.io/cad2019/content/Week15~Week18.html
心得:這次的測驗非常的難，不但要畫圖組裝，還要轉乘VREP跟WEBOT可以用的。

**Comment by s40723243** [comment]
心得:
這個禮拜的考察有點難，不僅要完成困難的繪圖，還要會導入vrep跟webot，希望可以在這堂課，學到更多東西。
影片(Vrep):https://youtu.be/blJILUWKwf8
影片(Webot):https://youtu.be/uPCe-5qKRA0
網頁:https://s40723243.github.io/cad2019/content/week15-18.html

**Comment by s40723236** [comment]
網頁 https://github.com/s40723236/cad2019

**Comment by s40523242** [comment]
心得 :這次對軟體不太熟，導致化太久
影片 https://youtu.be/H01SyMo6nKs

**Comment by s40723245** [comment]
心得:這次的小考題目很難，加上我對solvespace沒有很熟悉，導致零件只畫了一點就卡住了，之後會補上影片。
倉儲:https://s40723245.github.io/cad2019/content/week15-18.html

**Comment by s40723204** [comment]
心得:
利用solvespace繪製越野車是一個比較困難的任務，每個零件畫出來之後要將其組再一起會遇到許多困難，組裝完成後轉成stl檔就可以導入vrep相對比較簡單，轉成wrl後就可以導入webots也比較沒有問題。

**Comment by s40723242** [comment]
倉儲: https://github.com/s40723242/cad2019
網頁: https://s40723242.github.io/cad2019/content/week15-18.html

**Comment by s40723250** [comment]
心得:邁入第16周了,經過這周後,讓我了解到我對於之前練習的軟體還不夠熟悉,需要多練習

**Comment by s40723212** [comment]
還沒上完字幕時間就到了

**Comment by s40739214** [comment]
心得:因為不常使用solvespace，所以有點生疏，之後要多加練習。還要多練習v-rep和webot
影片:https://youtu.be/PtG_G3B92xM
網頁:https://github.com/s40739214/cad2019

**Comment by s40723227** [comment]
Week16網頁連結:https://s40723227.github.io/cad2019/content/Week15~Week18.html
影片連結˙:https://www.youtube.com/watch?v=g0nJGz4IKWs

**Comment by s40723246** [comment]
網頁:https://s40723246.github.io/cad2019/content/week15~18.html
影片:https://www.youtube.com/watch?v=flLLOELKO7g&feature=emb_logo
https://www.youtube.com/watch?v=vvA3EsJCb8o&feature=emb_logo

**Comment by s40723238** [comment]
金攤沒做完https://youtu.be/23344G_gs5Q

**Comment by s40723129** [comment]
心得 :這次對軟體不太熟，導致化太久
影片 https://www.youtube.com/watch?v=D-JsYBmJvZM
網頁 https://s40723237.github.io/cad2019/content/week15.html

**Comment by s40723123** [comment]
抱歉

**Comment by s40723222** [comment]
影片:https://www.youtube.com/watch?v=h3kaO5LzOr0
心得: 應為趕不上  所以只上影片
