### ISSUE TITLE
W17 2a 越野車零組件設計繪圖考試

### ISSUE THREAD

**Issue by mdecourse** [mdecourse/cad2019#37]
# 題目一: (各分組協同製作題)
請各組組長將 http://www.coppeliarobotics.com/helpFiles/en/buildingAModelTutorial.htm 與 https://cyberbotics.com/doc/guide/tutorial-2-modification-of-the-environment 等兩份教學內容, 平均分配給各組員, 經由翻譯了解操作過程後, 在各分組網站中, 以 "W17 協同任務" 作為頁面標題, 登錄各組員的分配表, 採用中英文並列的方式呈現兩份教學內容.

# 題目二: (各組員獨立製作題)
請參考下列影片中的機構設計, 從 https://github.com/mdecourse/cad2019/tree/master/downloads/solvespace/curiosity/ 擷取草圖設計概念, 利用 Solvespace 或 NX12 將原本車身與主連桿所採用的馬達鎖定設計, 改為機械阻尼(彈簧與極限定位)設計, 完成各零件的尺寸標示工程圖與 Engineering Bill of Material 後轉入 V-rep, 將所有 .slvs (或 .prt) 與 .ttt 檔案放入個人倉儲 downloads 目錄中的 w17/curiosity 目錄後, 將操作過程紀錄於個人網站中的 "W17 個人任務" 頁面中, 並嵌入一個至多 2 分鐘, 帶字幕的影片, 介紹說明操作過程與所完成的結果.

[![越野車模擬](https://img.youtube.com/vi/tVROknedL4U/0.jpg)](https://www.youtube.com/watch?v=tVROknedL4U)

完成上述兩題後, 請各組員將相關連結(包括題目一的個人貢獻連結與題目二的倉儲連結、網頁連結與影片連結), 放入下列回應中, 並針對所碰到的問題進行說明討論.

**Comment by s40723125** [comment]
W17 協同任務 https://s40723125.github.io/cad2019ag5/content/W17%20%E5%8D%94%E5%90%8C%E4%BB%BB%E5%8B%99.html
week17個人任務 https://youtu.be/zowdx4VmnIg
心得:把自走車畫好各部位零件後，利用solvespace組裝起來後，轉成stl直接宣告失敗原因不詳，只能說明我運氣不好或是不懂solvespace規則吧。

**Comment by s40723103** [comment]
影片:https://youtu.be/F8foQ2kmOts
倉儲連結:https://github.com/s40723103/cad2019/commits/master
任務一頁面連結:https://s40723103.github.io/cad2019/content/Week17.html
任務二頁面連結:https://s40723103.github.io/cad2019/content/week17-1.html
心得:在這一次的繪圖過程，阻礙滿滿，也很常繪圖到一半就錯誤然後必須刪除草圖，最後在時間緊迫下，硬是畫到一半而已，希望下次的考試能順手，也希望錯誤不要這麼多。

**Comment by s40723121** [comment]
W17
影片: [https://www.youtube.com/watch?v=kG8zRY-nxKo&feature=youtu.be](url)

心得:這周的翻譯讓我很頭痛加上英文又很爛只能依靠翻譯軟體 上傳時又發現GITHUB爆掉惹
只能借用同學倉儲上傳 最後一個禮拜裡得要好好檢視自己做了什麼

**Comment by s40723144** [comment]
翻譯內容:https://s40723145.github.io/cad2019ag2/content/40723144.html

**Comment by s40523113** [comment]
網頁連結:https://s40523113.github.io/cad2019/content/w17.html
倉儲:https://github.com/s40523113/cad2019

**Comment by s40723145** [comment]
網頁連結:https://s40723145.github.io/cad2019ag2/content/40723145.html
倉儲連結:https://github.com/s40723145/cad2019ag2/commits/master
心得:
在這次的任務中我並沒有達到題目二的要求，我對於模擬方面的設定知識還有太多不了解的部分導致於無法將馬達改為彈簧來做使用。在任務一除了自己翻譯的教材以外因為我是組長所以有很多的時間也花在解決組員pullrequest衝突的問題，回去之後要再多做嘗試。

**Comment by s40623252** [comment]
[40623252]心得:雖然今天有用solvespace做草圖跟翻譯英文但還是無法像影片中一樣模擬希望下次可以做得更好...
翻譯的連結:https://s40623252.github.io/cad2019/content/%E7%BF%BB%E8%AD%AF.html
影片的連結:https://youtu.be/azSeTQ8TK_k

**Comment by s40723136** [comment]
這週對於車的進度依舊緩慢，
任務一的內容可以觀看倉儲或是小組倉儲，
任務二沒有動靜，可能要再另外再花時間製作。
倉儲:https://github.com/s40723136/cad2019
小組倉儲:https://github.com/s40723148/cad2019ag1
影片:無

**Comment by s40723155** [comment]
影片：無
倉儲連結：https://github.com/s40723155/cad2019
W17題目一連結：https://s40723155.github.io/cad2019/content/week17.html
W17題目二連結：無
心得：針對題目一的部分，已經將分到的任務，去進行翻譯內容的工作了，並且順利的完成，題目二沒有如期完成，時間有點緊奏，晚點再將影片拍好再做上傳。

**Comment by s40523241** [comment]
W17 任務
翻譯:[https://s40723145.github.io/cad2019ag2/content/40523241.html](https://s40723145.github.io/cad2019ag2/content/40523241.html)
任務2來不及

**Comment by s40723114** [comment]
影片:https://youtu.be/D7lfLn-iibI
倉儲連結:https://github.com/s40723114/cad2019/commits/master
任務一頁面連結:https://s40723114.github.io/cad2019/content/webots%20tutorial.html
任務二頁面連結:https://s40723114.github.io/cad2019/content/w17%20%E6%9F%A5%E9%A9%973.html

心得:在這一次的任務中,對於solvespace繪製零組件變熟了,但還有很多進步空間,跟連桿的繪製技巧,還有v-rep導入問題

**Comment by s40723142** [comment]
W17:這禮拜任務有兩個一個是小組協同製作，一個是個人繪圖考試，本預計在第一節完成分組的協同任務，但是在push時，發生了合併的問題，直到最後一節課才發現是同時在進行更新導致問題的發生。
倉儲:https://github.com/s40723142/cad2019
個人網站:https://s40723142.github.io/cad2019/content/index.html

**Comment by s40723147** [comment]
提交連結:https://github.com/s40723147/cad2019/commits/master

頁面連結:https://s40723147.github.io/cad2019/content/W17.html

影片連結:https://youtu.be/kWpun7wbQ3o

學習心得: 今天的考試內容相當棘手，主因是不熟悉使用Solvespace繪製彈簧，也不會使用NX12繪製。所以在工程圖中繪製習用畫法表示其樣式已表示彈簧的造型‧需要更加努力!!

**Comment by s40723115** [comment]
40723115
倉儲https://s40723115.github.io/cad2019/content/W17%E5%8D%94%E5%90%8C%E4%BB%BB%E5%8B%99.html
心得
今天翻譯完後，在推近端的時候忘記git pull，所以造成衝突，最後也沒完成任務，會利用最後一個禮拜修理。

**Comment by s40723126** [comment]
倉儲連結:https://github.com/s40723126/cad2019/commits/master
任務一頁面連結:https://s40723126.github.io/cad2019/content/W17.html
心得:solvespace真的很難,一直失敗只好放棄沒有達到要求很抱歉

**Comment by s40723123** [comment]
翻譯連結
https://s40723104.github.io/cad2019ag3/content/Building%20a%20clean%20model%20tutorial.html
提交連結
https://github.com/s40723104/cad2019ag3/commits/master
我們這組只做了第一題因為目前沒有能力製作第二題以後會努力光是倉儲推送就有許多問題

**Comment by s40723118** [comment]
W17 協同任務:https://s40723145.github.io/cad2019ag2/content/index.html
心得:這次因為v-rep尚未熟練，導致無法做動；任務一有完成翻譯

**Comment by s40723134** [comment]
翻譯影片:https://www.youtube.com/watch?v=SYSyRYbo0jQ
倉儲:https://github.com/s40723134/cad2019
心得:這周進行了原文的翻譯以及拍攝,對於環境修改有了初步的認識,但畫圖依舊是毫無進展,下周前希望能做出簡單的操作

**Comment by s40723152** [comment]
影片:https://www.youtube.com/watch?v=qGcRXbB0JO8
倉儲連結:https://github.com/s40723152/cad2019
W17題目一:https://s40723152.github.io/cad2019/content/week17.html
W17題目二:https://www.youtube.com/watch?v=qGcRXbB0JO8
心得:由於這禮拜的分配時間的問題，翻譯時間佔用太多時間，導致任務二來不及放入個人網站中，下次我會好好分配時間，完成任務。

**Comment by s40723120** [comment]
個人:https://s40723120.github.io/cad2019/content/W17%E7%BF%BB%E8%AD%AF.html
翻譯內容:https://youtu.be/Mz2pQzV3eVA
心得:在這次任務當中光是翻譯就快要來不及了導致任務二沒有辦法再時限內完成

**Comment by s40723112** [comment]
影片:https://www.youtube.com/watch?v=DU0ptKz9mXQ&feature=youtu.be
倉儲連結:https://s40723112.github.io/cad2019/content/index.html
任務一:https://github.com/s40723148/cad2019ag1/commits?author=s40723112       https://s40723148.github.io/cad2019ag1/content/W17%E5%8D%94%E5%90%8C%E4%BB%BB%E5%8B%99.html
任務二:https://s40723112.github.io/cad2019/content/%E6%88%90%E6%9E%9C%E5%BD%B1%E7%89%87.html
心得:今天的時間還是很趕，時間分配還是不均

**Comment by s40723119** [comment]
心得:這次沒能解決複雜連桿的問題，將再研究讓已經導入的軸可以配合連桿
影片:https://www.youtube.com/watch?v=sT-M4kFX1AI
倉儲:https://s40723119.github.io/cad2019/content/week17.html

**Comment by s40723148** [comment]
提交連結:https://github.com/s40723148/cad2019ag1/commits/master

**Comment by s40723107** [comment]
個人倉儲 : https://github.com/s40723107/cad2019
個人網站 : https://s40723107.github.io/cad2019/content/index.html
影片 : https://s40723107.github.io/cad2019/content/week17%E5%BD%B1%E7%89%87.html
協同設計翻譯原文書 : https://s40723107.github.io/cad2019/content/%E5%8E%9F%E6%96%87%E6%9B%B8%E7%BF%BB%E8%AD%AF.html
心得 : 利用閱讀原文書，加上翻譯加上翻譯來吸取更多相關的知識，翻譯上有發生錯誤也謝謝老師的糾正 ，已經更改完成。

**Comment by s40723138** [comment]
倉儲:https://github.com/s40723138/cad2019
網頁:https://s40723138.github.io/cad2019/content/index.html
分組倉儲:https://s40723145.github.io/cad2019_group2/ 
影片:https://youtu.be/M5Xo2ARTumg
遇到問題:
隨身碟無故爆炸,V-rep,github,shareX皆無法使用,組員合併倉儲皆有問題,組員會不斷上傳自己檔案,使的與分組倉儲版本差距很大,加劇合併衝突.對題目不夠了解,令成品與題目有所差距,希望隊友能夠了解版本的重要.還有不夠努力不能解決隊友問題.

**Comment by s40523120** [comment]
影片:https://www.youtube.com/watch?v=jyomUbJ5OZg

**Comment by s40723110** [comment]
影片 https://youtu.be/i4RSGyaLB5s

**Comment by s40723150** [comment]
影片:https://youtu.be/TuqC8NBYWxc
倉儲連結:https://github.com/s40723150/cad2019
任務二頁面連結:https://s40723150.github.io/cad2019/content/W17%20%E5%80%8B%E4%BA%BA%E4%BB%BB%E5%8B%99.html
心得:

**Comment by s40723104** [comment]
網站:https://s40723104.github.io/cad2019/content/index.html
倉儲:https://github.com/s40723104/cad2019
心得:利用原文書翻譯了解了更多知識，但任務2因不熟悉V-REP所以沒在時間內完成

**Comment by s40723108** [comment]
沒影片
倉儲:https://s40723108.github.io/cad2019/content/index.html
任務一:https://s40723108.github.io/cad2019/content/w17.html
任務二:白
由於本人把分組網站用爆導致組員整體進度延後，感到深感抱歉

**Comment by s40623123** [comment]
分組網站:https://s40723147.github.io/cad2019ag4/content/index.html
倉儲連結https://github.com/s40623123/cad2019
心得:這次在翻譯過程中了解到更多更詳細得操作流程過程中也要一直去尋找更合適的翻譯內容及修改其文意

**Comment by s40723146** [comment]
網頁連結:https://s40723146.github.io/cad2019/content/index.html
個人倉儲:https://github.com/s40723146/cad2019
心得:翻譯翻的不是很通順，很多字的意思都連結不太起來
不過還是翻完了

**Comment by s40723119** [comment]
心得:解決了軸的問題，但還是解決不了連桿的問題
影片:https://www.youtube.com/watch?v=-SvBKndmr80
倉儲:https://s40723119.github.io/cad2019/content/week17.html

**Comment by s40723111** [comment]
W17 協同任務
倉儲連結:https://s40723111.github.io/cad2019/content/index.html
任務一:https://s40723111.github.io/cad2019/content/%E7%BF%BB%E8%AD%AF.html
任務二影片:https://www.youtube.com/watch?v=EMivR2bg4N8
心得:這周時間分配不太均勻，前面的翻譯花了太多時間，而加上種種問題加上對任務二的題目實在不太了解，不過這次翻譯之後了解到更多詳盡的流程，雖然對裡面翻譯的有些東西很陌生。

**Comment by s40723122** [comment]
影片:https://www.youtube.com/watch?v=Mipu3PtTbWE
倉儲連結:https://github.com/s40723122/cad2019
心得:這禮拜的翻譯速度有稍微變快了一些，可是整體英文能力還是需要加強

**Comment by s40723124** [comment]
影片網址:https://www.youtube.com/watch?v=3pob4r-935s&t=3s
個人倉儲:https://github.com/s40723124/cad2019
個人網站:https://s40723124.github.io/cad2019/content/index.html
心得:用google翻譯不會的單字，再將翻譯錯誤的單字修改成正確的，翻譯的過程中也讓我學習到了很多東西，但英文能力要再加強。

**Comment by 40723153** [comment]
任務一 個人貢獻 : https://s40723145.github.io/cad2019ag2/content/index.htmlhttps://s40723145.github.io/cad2019ag2/content/index.html
倉儲連結 : https://github.com/40723153/cad2019
網頁 : https://40723153.github.io/cad2019/content/W17.html
心得:翻譯任務一個人部分後,需要進行推送至分組倉儲,才能算是完成,但因為不大熟悉又怕會用爆倉儲就花了比其他人還長的時間
最後也沒有辦法完成第二部分的任務,剩下最後一周希望能繼續加油完成這學期的課題

**Comment by s40723132** [comment]
w17 協同任務
倉儲連結:https://github.com/s40723132/cad2019ag2.git
任務1:https://s40723132.github.io/cad2019ag2/content/40723132.html
分組網站:https://s40723145.github.io/cad2019ag2/content/index.html
影片:https://www.youtube.com/watch?v=H0-AchUZ24c
心得: 人生好難

**Comment by s40723137** [comment]
個人倉儲：https://s40723137.github.io/cad2019/content/W17%E5%80%8B%E4%BA%BA%E4%BB%BB%E5%8B%99.html
分組倉儲：
https://github.com/s40723147/cad2019ag4

在分組網頁中遇到pull request的問題，弄了太久導致拖到翻譯及任務二的進度

**Comment by s40723130** [comment]
網站:https://s40723130.github.io/cad2019/content/W17%202a.html
影片:https://www.youtube.com/watch?v=r9yGWK-bGBs&feature=youtu.be
心得:題目二看影片種覺得還蠻簡單的，但實際做起來卻處處碰壁。

**Comment by s40723154** [comment]
心得 : 接近期末了 終於成功把東西推上去了 這期間雖然努力嘗試過很多次 也尋求許多人的協助 卻始終沒有辦法 但是就在今天 我做了教學內容的翻譯 並且成功的推上去了 
倉儲 : https://github.com/s40723154/cad2019
網站 : https://s40723154.github.io/cad2019/content/%E6%AF%8F%E5%91%A8%E9%80%B2%E5%BA%A6.html

**Comment by s40723141** [comment]
個人倉儲連結：https://github.com/s40723141/cad2019
小組倉儲連結：https://github.com/s40723141/cad2019_group2
個人網站：https://s40723141.github.io/cad2019/content/index.html
心得：對solvespace、vrep等操作不熟悉導致過程中產生許多錯誤，不適合錄製成影片，對自己非常失望。

**Comment by s40723102** [comment]
https://studio.youtube.com/video/CCdi7The8wc/edit
https://github.com/s40723102/cad2019/commits/master
時間分配不均 來不及組裝處處碰壁

**Comment by s40723101** [comment]
w17
影片連結:https://www.youtube.com/watch?v=0ipB-n0iA4o
心得:任務二的 題目看起來不難，但實際上超級困難的
