### ISSUE TITLE
W17 2b 越野車零組件設計繪圖考試

### ISSUE THREAD

**Issue by mdecourse** [mdecourse/cad2019#38]
# 題目一: (各分組協同製作題)
請各組組長將 http://www.coppeliarobotics.com/helpFiles/en/buildingAModelTutorial.htm 與 https://cyberbotics.com/doc/guide/tutorial-2-modification-of-the-environment 等兩份教學內容, 平均分配給各組員, 經由翻譯了解操作過程後, 在各分組網站中, 以 "W17 協同任務" 作為頁面標題, 登錄各組員的分配表, 採用中英文並列的方式呈現兩份教學內容.

# 題目二: (各組員獨立製作題)
請參考下列影片中的機構設計, 從 https://github.com/mdecourse/cad2019/tree/master/downloads/solvespace/curiosity/ 擷取草圖設計概念, 利用 Solvespace 或 NX12 將原本車身與主連桿所採用的馬達鎖定設計, 改為機械阻尼(彈簧與極限定位)設計, 完成各零件的尺寸標示工程圖與 Engineering Bill of Material 後轉入 V-rep, 將所有 .slvs (或 .prt) 與 .ttt 檔案放入個人倉儲 downloads 目錄中的 w17/curiosity 目錄後, 將操作過程紀錄於個人網站中的 "W17 個人任務" 頁面中, 並嵌入一個至多 2 分鐘, 帶字幕的影片, 介紹說明操作過程與所完成的結果.

[![越野車模擬](https://img.youtube.com/vi/tVROknedL4U/0.jpg)](https://www.youtube.com/watch?v=tVROknedL4U)

完成上述兩題後, 請各組員將相關連結(包括題目一的個人貢獻連結與題目二的倉儲連結、網頁連結與影片連結), 放入下列回應中, 並針對所碰到的問題進行說明討論.

**Comment by s40723204** [comment]
影片 :https://youtu.be/H--Yj6Q0ris
個人倉儲 :https://github.com/s40723204/cad2019
個人網站:https://s40723204.github.io/cad2019/content/week15-18.html
任務一 : https://s40723204.github.io/cad2019bg4/content/week17%E5%8D%94%E5%90%8C%E4%BB%BB%E5%8B%99.html
利用vrep導入車體後要更改輪子及輪軸的參數，不然車子跑起來會很慢幾乎沒在動。增加木箱的數值也要調好不然箱子會掉下去，沒增加木箱之前車子作動會掉下去，木箱沒有固定好車子也無法順利經過。

**Comment by s40723243** [comment]
影片:https://www.youtube.com/watch?v=ZlUL-lxG5uM&feature=youtu.be
個人倉儲:https://github.com/s40723243/cad2019
個人網站:https://s40723243.github.io/cad2019/content/week15-18.html
https://s40723243.github.io/cad2019/content/week15-18.html
任務一:
https://s40723204.github.io/cad2019bg4/content/week17%E5%8D%94%E5%90%8C%E4%BB%BB%E5%8B%99.html
利用vrep打開老師的零件車，並且新增一些方塊來讓車子經過，以及改變輪軸的參數，雖然我的木箱沒有固定好，但是車子還是有順利通過。

**Comment by s40723213** [comment]
分組網站:https://s40723204.github.io/cad2019bg4/content/week17%E5%8D%94%E5%90%8C%E4%BB%BB%E5%8B%99.html
個人倉儲:https://s40723213.github.io/cad2019/content/Week15-18.html
個人網站:https://github.com/s40723213/cad2019
影片連結:https://www.youtube.com/watch?v=uMIY6tqvORg
心得:我的車子故障，只好借老師的車子，結果新手上路還不熟，實在動不了。下次加油。fight

**Comment by s40723241** [comment]
影片: https://youtu.be/Fs8DIuGvJ3E
倉儲: https://github.com/s40723241/cad2019
任務一:
https://s40723206.github.io/cad2019bg3/content/W17%20%E5%8D%94%E5%90%8C%E4%BB%BB%E5%8B%99.html
https://github.com/s40723206/cad2019bg3/commits/master
任務二: https://s40723241.github.io/cad2019/content/WEEK15-18.html

心得: 本周的測驗讓我們把越野車的模組導入到Vrep裏頭，然後設定輪軸參數之類的，接著開始模擬越野車遇到障礙物的情況，看到車子把障礙物輾過去真的非常有成就感!

**Comment by s40723239** [comment]
倉儲:https://github.com/s40723239/cad2019
影片:https://youtu.be/V7ApAskcuag
任務1:
https://s40723239.github.io/cad2019/content/Building%20a%20clean%20model%20tutorial%C2%A0%E7%BF%BB%E8%AD%AF.html
任務2: https://s40723239.github.io/cad2019/content/Week15~Week18.html
https://s40723239.github.io/cad2019/content/Week15~Week18.html
心得: 首先與組員討論翻譯內容分配，大家都很快的把東西趕出來，讓組長有時間把翻譯內容貼到分組網站上，再來就是執行任務2 很謝謝我的組員教會我怎麼設定參數，讓我有機會再去教其他人

**Comment by s40723238** [comment]
影片:https://www.youtube.com/watch?v=WjpM5M4Hr90
倉儲:https://github.com/s40723238/cad2019
任務一連結:
https://s40723206.github.io/cad2019bg3/content/Building%20a%20clean%20model%20tutorial.html
任務二連結:https://s40723238.github.io/cad2019/content/week15-18.html
心得:今天到底在做甚麼我完全看不懂，還好有厲害的同學有先做影片嚷我借鑑。

**Comment by s40723203** [comment]
任務1:https://github.com/s40723206/cad2019bg3
個人網站:https://s40723203.github.io/cad2019/content/week15-18.html
個人倉儲:https://github.com/s40723203/cad2019/commits/master
影片連結:https://youtu.be/kBnsERS3UOE
心得:
一開始聽到這週任務時很慌，毫無頭緒。開始操作發現其實還蠻好玩的，從繪圖到使其作動，越來越有興趣並將它完成。很開心能夠學到新的東西。也謝謝幫助我的同學們，讓我能及時完成。

**Comment by s40723205** [comment]
心得:這次的小考，分為題目一跟題目二，題目一的翻譯還算ok但是題目二就有點不知所措了，對於尼組的設定，我幾乎不知道該怎麼做，所以只有先把車子跟障礙物抓到V-REP裡面而已，我發現對於V-REP我還有很多需要多多了解。
倉儲: https://github.com/s40723205/cad2019
網頁: https://s40723205.github.io/cad2019/content/Week17.html
影片: https://www.youtube.com/watch?v=jhw5E_mx42Y

**Comment by s40723218** [comment]
個人倉儲:https://github.com/s40723218/cad2019
個人網站:https://s40723218.github.io/cad2019/content/index.html
任務一:https://s40723218.github.io/cad2019/content/week15-18.html
影片:https://www.youtube.com/watch?v=JXF8rkA3jLo&feature=youtu.be
心得:這禮拜的考試內容有點多且有難度，因此時間上沒有控制好，所以沒有完全完成，往後會加緊利用時間去補齊的。

**Comment by s40723221** [comment]
影片連結:https://studio.youtube.com/video/2zJejyISYxY/edit
個人網站連結https://s40723221.github.io/cad2019/content/week15-18.html
要做到能夠動的車子模擬是非常困難的，現階段我們只能夠對車子做外型上的變更，在WEBOTS上能夠做到的移動和跨過障礙物的動作但是還是必須理解內容才有辦法繼續設定。

**Comment by s40723227** [comment]
個人任務影片:https://youtu.be/glO7gAJjWpo
個人倉儲:https：// s40723227.github.io/cad2019/content/Week15-18.html
個人網站：https : //github.com/s40723227/cad2019

**Comment by s40723240** [comment]
個人網站:https://s40723240.github.io/cad2019/content/Week15-18.html
個人倉儲:https://github.com/s40723240/cad2019
任務1:https://s40723240.github.io/cad2019/content/v-rep%E7%BF%BB%E8%AD%AF.html
心得: 發現做不完，希望有清醒的腦袋繼續堅持下去，把困難給克服。

**Comment by s40723249** [comment]
影片: https://www.youtube.com/watch?v=_dQdgv7oQHM&feature=emb_logo
個人倉儲: https://github.com/s40723249/cad2019
個人網站: https://s40723249.github.io/cad2019/content/WEEK17%E5%80%8B%E4%BA%BA%E4%BB%BB%E5%8B%99.html
心得:任務一以翻譯完，但小組倉儲出了問題會再補。這次利用VREP設定各種參數，並設定方塊讓車子行駛過去。雖然不熟悉，但會慢慢練習。

**Comment by s40739214** [comment]
影片連結:https://youtu.be/AWhDOZqJ8oQ
個人網站:https://s40739214.github.io/cad2019/content/week15-18.html
個人倉儲:https://github.com/s40739214/cad2019
任務一:https://github.com/s40723206/cad2019bg3
心得:由組長分配翻譯內容，讓大家分工合作將東西用好。過程中要讓車子動有些困難，需要再多理解。

**Comment by s40723247** [comment]
題目(一)與(二)個人貢獻連結:https://s40723247.github.io/cad2019/content/week15-18.html
個人倉儲連結:https://github.com/s40723247/cad2019
影片連結:https://www.youtube.com/watch?v=79gmsYUKfN4
心得:
這次的任務比之前在更難了，要將原本車身與主連桿所採用的馬達鎖定設計, 改為機械阻尼設計，這個我真的不怎麼會，只能先把簡單的部分先做一做，把該拿的分數拿到，總比放棄好。希望能夠越來越好 !

**Comment by s40723250** [comment]
個人網站:https://s40723250.github.io/cad2019/content/WEEK16~18.html
個人倉儲:https://github.com/s40723250/cad2019
心得:這一周做的東西有點多,雖然任務1有做完,但任務2的部分卻無法完成,需要多練習幾次才能熟練

**Comment by s40723246** [comment]
W17網址:https://s40723246.github.io/cad2019/content/week15~18.html
個人網站:https://s40723246.github.io/cad2019/content/index.html
本次影片:https://youtu.be/0LYQDLtd1cg
心得:這次繪畫了solvespace繪製了車體的各個零件，再將其一一組合，在其中我感受到自己在學習，從無到有的車子，讓我把它組合出來，是有成就的，再來是導入VERP，雖然我還不能讓車子運作順暢，但經過我日後的學習，我會讓他能夠運作。

**Comment by s40723244** [comment]
倉儲:https://github.com/s40723244/cad2019
影片:https://youtu.be/6pxnOWrnivo
任務1:
https://s40723212.github.io/cad2019bg1/content/%E5%8A%89%E5%86%A0%E5%BF%97.html
任務2: https://s40723244.github.io/cad2019/content/week17.html
心得: 這次的考試很符合我們的協同的定義，讓大家都能有效的利用分工完成報告，不過關於協同還是有很大的問題，組員很多都還不曉得協同的操作方式，希望未來能夠漸漸熟悉。

**Comment by s40723229** [comment]
個人網站連結:https://s40723229.github.io/cad2019/content/week15-18.html
個人倉儲:https://github.com/s40723229/cad2019
心得:關於今天的任務二我完全無法理解，所以無法在時間內完成任務，回去後再繼續研究如何完成

**Comment by s40723216** [comment]
個人網站:https://s40723216.github.io/cad2019/content/index.html
本次影片:https://s40723216.github.io/cad2019/content/index.html
心的:這次終於有影片以及做出東西了，在下周結算前我會把前面的洞補起來的

**Comment by s40723237** [comment]
影片https://youtu.be/1lFyHZdmK1I
心得: 這次把東西放到vrep後有點bug無法放大和縮小跟移動角度 所以也還沒做完

**Comment by s40723210** [comment]
個人網站連結:https://s40723210.github.io/cad2019/content/Week15-18.html
youtube影片連結:https://youtu.be/2hmV_pxAXsY
[![V-rep 模擬範例](http://img.youtube.com/vi/2hmV_pxAXsY/0.jpg)](https://www.youtube.com/watch?v=2hmV_pxAXsY)

**Comment by s40723212** [comment]
倉儲:https://github.com/s40723212/cad2019
個人網站:https://s40723212.github.io/cad2019/content/index.html

下次我會掌握時間，不要花太多時間除錯

**Comment by s40723234** [comment]
影片影片 :https://www.youtube.com/watch?v=dlanmIau7f4
個人倉儲 :https://github.com/s40723234/cad2019
個人網站:https://s40723234.github.io/cad2019/content/week15-18.html

因為我的分組網站內容出現了一些問題，在4:00前可能無法解決，故我將week17的翻譯內容(任務一)先放到個人倉儲，我會在下課處理好，利用vrep導入車體後要更改輪子及輪軸的參數是本周的內容。

**Comment by s40723233** [comment]
題目一的個人貢獻連結:https://s40723206.github.io/cad2019bg3/content/Building%20a%20clean%20model%20tutorial.html
題目二的倉儲連結:https://github.com/s40723233/cad2019
題目二的網頁連結:https://s40723233.github.io/cad2019/content/W17%20%E5%80%8B%E4%BA%BA%E4%BB%BB%E5%8B%99.html
題目二的影片連結:https://youtu.be/4lgwxk64cqY
心得:這一次的考試要把車子的馬達鎖定設計, 改為機械阻尼設計，結果我毫無頭緒，我還是把車子導入到VERP跑了一下希望未來能更加熟練。

**Comment by s40723242** [comment]
影片: https://youtu.be/5Eu5uiQxTNA
倉儲: https://github.com/s40723242/cad2019
個人網站:https://s40723242.github.io/cad2019/content/index.html
任務一:https://s40723242.github.io/cad2019/content/week15-18.html
任務二: https://s40723242.github.io/cad2019/content/week15-18.html
心得: 本周的測驗讓我們把越野車的模組導入到Vrep，並增加圓桿讓支架再越過障礙物時能穩定通過，雖然距離獨立設計還很久，但我希望下學期的課程。

**Comment by s40723207** [comment]
影片:https://youtu.be/mtHohH9Z64M
心得:學校電腦中毒，倉儲上傳不了，翻譯做完了，回去再弄。

**Comment by s40723232** [comment]
倉儲:https://s40723232.github.io/cad2019/content/index.html
任務1:
https://s40723232.github.io/cad2019/content/%E6%A7%8B%E5%BB%BA%E4%B9%BE%E6%B7%A8%E7%9A%84%E6%A8%A1%E5%9E%8B%E6%95%99%E7%A8%8B%20%E7%BF%BB%E8%AD%AF.html
任務2:https://www.youtube.com/watch?v=EIHpupWhES8
心得:這周東西有點多，可是都不會太難，可是真的太多了。

**Comment by s40723219** [comment]
任務一:https://s40723219.github.io/cad2019/content/Building%20a%20clean%20model%20tutorial.html
任務二:https://www.youtube.com/watch?v=llffkZeg4L0&feature=youtu.be
倉儲:https://s40723219.github.io/cad2019/content/index.html
影片:https://www.youtube.com/watch?v=llffkZeg4L0&feature=youtu.be
心得:這次將模型車導入連接軸並設置路障，過程中雖然有諸多不了解的地方，單還是成功做出來了

**Comment by s40723245** [comment]
個人網站:https://s40723245.github.io/cad2019/content/week15-18.html
個人倉儲:https://github.com/s40723245/cad2019
任務一:https://s40723245.github.io/cad2019/content/week15-18.html
任務二:https://s40723245.github.io/cad2019/content/week15-18.html
心得:這次組裝越野車零件的時候處處碰壁，要連結零件一直出現干涉，導致時間不夠用V-rep模擬，回去會補上進度。

**Comment by s40723209** [comment]
影片:https://www.youtube.com/watch?v=OQ_rg7D2rFw&feature=youtu.be
個人倉儲:https://github.com/s40723209/cad2019
個人網站:https://s40723209.github.io/cad2019/content/week15~18.html
心得:任務一由組長分配，任務二有點難，一開始不知道要做什麼，需要多練習幾次才能熟練。

**Comment by s40723228** [comment]
心得:還沒做完，回去繼續做

**Comment by s40723223** [comment]
TASK2:https://www.youtube.com/watch?v=VestKYVkFGk&feature=youtu.be
TASK1:https://s40723223.github.io/cad2019/content/Week15~18.html
倉儲:https://github.com/s40723223/cad2019/commits/master
心得:終於敢出來，很刺激。

**Comment by s40723222** [comment]
倉儲:https://github.com/s40723222/cad2019
任務一翻譯:https://s40723222.github.io/cad2019/content/Weeks%2015~18.html
https://s40723222.github.io/cad2019/content/Weeks%2015~18.html
心得: 做不完

**Comment by s40723206** [comment]
w17分組協同任務:
Building a clean model tutorial:https://s40723206.github.io/cad2019bg3/content/Building%20a%20clean%20model%20tutorial.html
Webots User Guide Tutorial 2:https://s40723206.github.io/cad2019bg3/content/Webots%20User%20Guide%20Tutorial%202.html
任務二來不及做因為在整理分組網頁時一直出錯推不上去，抱歉。
心得:做得比較趕只有把任務一做完，因為要整理組員的東西推送時又出錯所以做不完，但回去還是會去繼續做，把該做的完成。
