### ISSUE TITLE
2a cad2019 期末報告影片繳交處

### ISSUE THREAD

**Issue by mdecourse** [mdecourse/cad2019#41]
1. 請每位學員透過個人的 reveal.js 網際簡報作為引導, 拍攝一個**至多 2 分鐘**而且**包含詳細說明字幕**的影片, 上傳到個人的 Youtube 帳號下後, 嵌入個人網站中的"期末報告"頁面中, 再將**網頁連結**與**影片連結**回報至下列留言區.

2. 各組組員請登入 @gm 電子郵箱帳號, 檢視各組員帳號下各週與期末報告頁面中的內容與影片後, 至電腦輔助設計實習自評與互評表單: https://forms.gle/raTtrfjv8cMMVSZd6 , 完成**各週自評與互評**.

**Comment by mdecourse** [comment]
2a 即時自評表: https://ethercalc.org/wrjwp1odms5m

**Comment by s40723119** [comment]
網站:https://s40723119.github.io/cad2019/content/%E6%9C%9F%E6%9C%AB%E5%A0%B1%E5%91%8A.html
影片:https://www.youtube.com/watch?v=Q78gFc9iKnM

**Comment by s40523113** [comment]
網頁連結:https://s40523113.github.io/cad2019/content/%E6%9C%9F%E6%9C%AB%E5%A0%B1%E5%91%8A.html
影片連結:https://www.youtube.com/watch?v=Sr3WvZG0GV8

**Comment by s40723108** [comment]
網站:https://s40723108.github.io/cad2019/content/index.html
影片:https://www.youtube.com/watch?v=xpVKHOhLguQ

**Comment by s40723142** [comment]
個人網站:https://s40723142.github.io/cad2019/content/index.html
期末影片:https://youtu.be/3k6KSFuJgbY

**Comment by s40523241** [comment]
[期末報告](https://s40523241.github.io/cad2019/content/%E6%9C%9F%E6%9C%AB%E5%A0%B1%E5%91%8A.html)
[簡報連結](https://s40523241.github.io/cad2019/reveal/index.html#/)

**Comment by s40723136** [comment]
影片位置:https://www.youtube.com/channel/UCCkkl-lhe1eX8mlYYH-S1Rw
網頁連結:https://s40723136.github.io/cad2019

**Comment by s40723112** [comment]
網頁連結:https://s40723112.github.io/cad2019/content/index.html
影片連結:https://www.youtube.com/watch?v=569IN8vSt6g&feature=youtu.be

**Comment by s40723138** [comment]
影片連結:https://youtu.be/qtiSOyafK4Q

**Comment by s40723103** [comment]
影片連結:https://youtu.be/AtZnOuynz-c
網頁連結:https://s40723103.github.io/cad2019/content/%E6%9C%9F%E6%9C%AB%E8%80%83.html

**Comment by s40723107** [comment]
個人網站 : https://s40723107.github.io/cad2019/content/index.html
個人倉儲 : https://github.com/s40723107/cad2019
https://github.com/s40723107/cad2019
期末影片連結 : https://www.youtube.com/watch?v=iHYnPkxkPw4&feature=youtu.be

**Comment by s40723123** [comment]
期末影片:https://www.youtube.com/watch?v=hIVOYt2Gjz4
網站連結:https://s40723123.github.io/cad2019/content/index.html

**Comment by s40723114** [comment]
個人網站:
https://s40723114.github.io/cad2019/content/%E6%9C%9F%E6%9C%AB%E5%A0%B1%E5%91%8A.html
期末影片:
https://youtu.be/Js5LrzpPjmc

**Comment by s40723154** [comment]
影片:https://youtu.be/vO1Ey24Bnqw
網頁:https://s40723154.github.io/cad2019/content/w18.html

**Comment by s40723121** [comment]
網站: [https://s40723121.github.io/cad2019/content/index.html](url)
影片: [https://www.youtube.com/watch?v=le5huQKkgjM](url)

**Comment by s40723124** [comment]
影片連結:https://www.youtube.com/watch?v=tvp-g1NDQPY
網頁連結:https://s40723124.github.io/cad2019/content/index.html
倉儲連結:https://github.com/s40723124/cad2019

**Comment by s40723110** [comment]
期末影片 : https://youtu.be/TXioY5xkM2I
個人網站 : https://s40723110.github.io/cad2019/content/index.html

**Comment by s40723148** [comment]
影片:https://youtu.be/auZmbYCp0PA
倉儲:https://github.com/s40723148/cad2019

**Comment by s40723125** [comment]
期末影片:https://youtu.be/E_acw6pJ6Bo
網站連結:https://s40723125.github.io/cad2019/content/%E6%9C%9F%E6%9C%AB%E5%A0%B1%E5%91%8A.html

**Comment by s40723132** [comment]
網頁連結:https://s40723132.github.io/cad2019/content/index.html
影片連結:https://studio.youtube.com/video/J5a_sQrpFkw/edit
倉儲連結:https://github.com/s40723132/cad2019

**Comment by s40723147** [comment]
網站連結:
https://s40723147.github.io/cad2019/content/%E6%9C%9F%E6%9C%AB%E5%A0%B1%E5%91%8A.html
影片連結:
https://youtu.be/kvodmbpPijQ

**Comment by s40723115** [comment]
40723115
影片:https://www.youtube.com/watch?v=XvULfMmkvLg&feature=youtu.be
倉儲:https://s40723115.github.io/cad2019/content/index.html
SSH設定跑掉Reveal沒辦法推送

**Comment by 40723153** [comment]
影片:https://youtu.be/ARLVDQ8H_IY
個人網頁:https://40723153.github.io/cad2019/content/CH9.html

**Comment by s40723120** [comment]
影片連結:https://www.youtube.com/watch?time_continue=3&v=8UsZJIR-NyY
網站連結:https://s40723120.github.io/cad2019/content/

**Comment by s40723134** [comment]
個人網站:https://s40723134.github.io/cad2019/content/index.html
個人倉儲:https://github.com/s40723134/cad2019
期末影片:https://www.youtube.com/watch?v=iKQstKXeKYc

**Comment by s40723120** [comment]
網站連結:https://s40723120.github.io/cad2019/content/
影片連結:https://www.youtube.com/watch?v=8UsZJIR-NyY

**Comment by s40723155** [comment]
個人倉儲：https://github.com/s40723155/cad2019
網站連結：https://s40723155.github.io/cad2019/content/index.html
期末影片：https://www.youtube.com/watch?v=fntttp_PHlM

**Comment by s40723102** [comment]
網站連結:https://s40723102.github.io/cad2019/content/index.html
影片:https://youtu.be/u5lp_uiQM_4

**Comment by s40723150** [comment]
網站連結:
https://s40723150.github.io/cad2019/content/%E6%9C%9F%E6%9C%AB%E5%A0%B1%E5%91%8A.html
影片連結:
https://youtu.be/Geqz7Eyk5bs

**Comment by s40723111** [comment]
個人倉儲:https://github.com/s40723111/cad2019
個人網站:https://s40723111.github.io/cad2019/content/index.html
期末影片:https://www.youtube.com/watch?v=FcvdItlIpP4

**Comment by s40723118** [comment]
影片網址:https://youtu.be/lRMD9JFHS0c
網頁連結:https://s40723118.github.io/cad2019/content/index.html

**Comment by s40723152** [comment]
網站連結:https://s40723152.github.io/cad2019/content/%E6%9C%9F%E6%9C%AB%E5%A0%B1%E5%91%8A.html
影片連結:https://www.youtube.com/watch?v=TYjpl-IS858

**Comment by s40723137** [comment]
個人網站:https://s40723137.github.io/cad2019/content/%E5%AD%B8%E7%BF%92%E6%88%90%E6%9E%9C%E5%9B%9E%E5%A0%B1.html
倉儲:https://github.com/s40723137/cad2019
影片在網站中

**Comment by s40623252** [comment]
[40623252]雖然今天有作影片但reveal.js無法執行
翻譯的連結:https://s40623252.github.io/cad2019/content/%E7%BF%BB%E8%AD%AF.html
影片的連結:(1)https://youtu.be/LVcR6oo-v3Q
(2)https://youtu.be/azSeTQ8TK_k
個人倉儲：https://github.com/s40623252/cad2019
個人網站：https://s40623252.github.io/cad2019/content/index.html

**Comment by s40723141** [comment]
影片連結：https://www.youtube.com/watch?v=vohz8vSP0O0
倉儲連結：https://github.com/s40723141/cad2019
網頁連結：https://s40723141.github.io/cad2019/content/index.html

**Comment by s40723145** [comment]
個人網站:https://s40723145.github.io/cad2019/content/index.html
影片連結:https://youtu.be/bHbsxU-guOQ

**Comment by s40723104** [comment]
個人網站:https://s40723104.github.io/cad2019/content/index.html
個人倉儲:https://github.com/s40723104/cad2019
影片:https://youtu.be/3ASwYDwShmw

**Comment by s40723140** [comment]
影片連結：https://www.youtube.com/watch?v=sutDyvYQWgc
個人網站 : https://s40723140.github.io/cad2019/content/

**Comment by s40723146** [comment]
影片:https://www.youtube.com/watch?v=ozow-EwntCc&feature=youtu.be
個人網站:https://s40723146.github.io/cad2019/content/index.html
個人倉儲:https://github.com/s40723146/cad2019

**Comment by s40723101** [comment]
個人倉儲:https://s40723101.github.io/cad2019/
影片:https://www.youtube.com/watch?v=MM6NOxlRzGc

**Comment by s40723106** [comment]
個人倉儲 :https://github.com/s40723106/cad2019

**Comment by s40623123** [comment]
網站:https://s40623123.github.io/cad2019/content/index.html
影片:https://www.youtube.com/channel/UCIHS_Sy4vshyh7DhCfUnSAg?view_as=subscriber

**Comment by s40723144** [comment]
影片:https://www.youtube.com/watch?v=6mr0NyQeghU

**Comment by s40723127** [comment]
倉儲連結:https://github.com/s40723127/cad2019
影片連結:https://youtu.be/C7vEZgBVBXc

**Comment by s40723101** [comment]
個人網站:https://s40723101.github.io/cad2019/content/index.html
個人倉儲:https://s40723101.github.io/cad2019/
影片:https://www.youtube.com/watch?v=MM6NOxlRzGc

**Comment by s40723130** [comment]
網站:https://s40723130.github.io/cad2019/content/index.html
影片:https://www.youtube.com/watch?v=g7hVEzNSG2I&feature=youtu.be

**Comment by s40523120** [comment]
倉儲 https://github.com/s40523120/cad2019

**Comment by s40723144** [comment]
網頁:https://s40723144.github.io/cad2019/content/%E6%9C%9F%E6%9C%AB%E5%A0%B1%E5%91%8A.html
影片:https://www.youtube.com/watch?v=6mr0NyQeghU

**Comment by s40723140** [comment]
個人倉儲:https://github.com/s40723140/s40723140.github.io
影片: https://www.youtube.com/watch?v=sutDyvYQWgc
